JuliaApproximation/ApproxFunBase.jl

src/specialfunctions.jl

the dims keyword in now required for cat

---

Project.toml
src/Caching/blockbanded.jl
src/Operators/Operator.jl
src/Operators/general/InterlaceOperator.jl
src/testing.jl

Fixes https://github.com/JuliaApproximation/ApproxFun.jl/issues/771

Use Block{1} in blockcol/rowsupport

---

Project.toml
src/Caching/blockbanded.jl
src/Operators/nullspace.jl

From `ApproxFun` tests, e.g. https://github.com/JuliaApproximation/ApproxFunBase.jl/runs/7462829852?check_suite_focus=true

Fix deprecations as suggested in tests

---

Project.toml
src/Operators/general/algebra.jl
test/runtests.jl

This makes the code simpler, while leaving functionality unchanged.
Also, bugfix in
```julia
julia> Z = ZeroOperator();
julia> Z + Z + Z;
```

Orthogonalize `PlusOperator` and `TimesOperator` unwrapping

---

Project.toml
src/ApproxFunBase.jl
src/show.jl
test/runtests.jl
test/show.jl

Not everything is tested yet, but downstream tests should indicate the success for now.

Move `show` methods from `ApproxFun`

---

Project.toml
src/show.jl
test/show.jl

After this:
```julia
julia> Q = QuotientSpace(Dirichlet(ConstantSpace(0..1)))
ConstantSpace(0..1) /
1.0
1.0
julia> show(Q)
ConstantSpace(0..1) /
DirichletWrapper : ConstantSpace(0..1) → 2-element ArraySpace:
ConstantSpace{DomainSets.Point{Int64}, Float64}[ConstantSpace(DomainSets.Point{Int64}(0)), ConstantSpace(DomainSets.Point{Int64}(1))]
```

fix `show` for `QuotientSpace`

---

src/Operators/Operator.jl
src/Operators/SubOperator.jl
test/runtests.jl

Index SubOperator with colon (backport to v0.5)

---

Project.toml

Version bump to v0.6.3

---

src/Fun.jl
test/SpacesTest.jl

Ref https://github.com/JuliaApproximation/ApproxFun.jl/issues/731

plus for a single Fun

---

Project.toml
src/Space.jl
test/SpacesTest.jl

Now the following works
```julia
julia> f = Fun(x->x^2, Chebyshev())
Fun(Chebyshev(), [0.5, 0.0, 0.5])
julia> v = coefficients(f, Chebyshev(), Legendre())
3-element Vector{Float64}:
0.33333333333333337
0.0
0.6666666666666666
```

coefficient conversion bugfix

---

Project.toml
src/Caching/banded.jl
src/Caching/matrix.jl
src/LinearAlgebra/helper.jl
src/Operators/SubOperator.jl
src/Operators/general/algebra.jl
src/Operators/ldiv.jl
src/Operators/qr.jl
src/Space.jl
test/SpacesTest.jl

With this PR, the following work:
```julia
julia> v = rand(10);
julia> itransform!(Legendre(), transform!(Legendre(), v)) ≈ v
true
julia> itransform!(NormalizedLegendre(), transform!(NormalizedLegendre(), v)) ≈ v
true
```
Similarly, for various other spaces.

Inplace polynomial transforms

---

src/specialfunctions.jl
test/runtests.jl

This PR improves some intermediate type inference in `exp(x)`. Let's see if the CI passes with this

improve inference in tolerance in exp

---

src/ApproxFunBase.jl
src/Operators/ldiv.jl
src/specialfunctions.jl

These were not being extended.

import rad2deg/deg2rad from Base

---

src/Operators/Operator.jl
src/Operators/banded/CalculusOperator.jl
src/Operators/banded/Reverse.jl
src/Operators/functionals/CalculusFunctional.jl
src/Operators/general/algebra.jl
src/constructors.jl

Also, avoid excessive specialization in several functions, such as `default_fun` and `zeros`

Reduce `Meta.parse` calls

---

src/Operators/general/algebra.jl
src/show.jl

Also, make `PrintShow` concrete
Let's see if the CI passes with this.

Type asesrtions in `BandedMatrix` conversion

---

.github/workflows/downstream.yml
src/Fun.jl

Just to see if the CI fails anywhere

Make fun immutable

---

Project.toml
src/Operators/general/algebra.jl
test/runtests.jl

```julia
julia> f = Fun(PointSpace(1:3), Float64[1:3;]);
julia> M = Multiplication(f);
julia> T = M * M;
julia> @inferred adjoint(T);
```

Inference in TimesOperator adjoint/transpose

---

src/Multivariate/ProductFun.jl

Fixes https://github.com/JuliaApproximation/ApproxFun.jl/issues/758.

Fix wrong type casting in ProductFun evaluation

---

src/Fun.jl
test/SpacesTest.jl

After this, something like this will work:
```julia
julia> f = Fun(Chebyshev(), SA[1,2,3.0])
Fun(Chebyshev(), [1.0, 2.0, 3.0])
julia> f*f
Fun(Chebyshev(), [7.5, 10.0, 8.0, 6.0, 4.5])
```

convert to vector in chop

---

Project.toml
src/Operators/banded/CalculusOperator.jl
test/SpacesTest.jl

This fixes a bug in evaluating derivatives in normalized spaces. Tests will have to wait for https://github.com/JuliaApproximation/ApproxFunOrthogonalPolynomials.jl/pull/74, as they depend on each other to work.

derivative for normalized spaces

---

src/Caching/matrix.jl
src/Caching/ragged.jl
src/Fun.jl
src/Operators/banded/Multiplication.jl
test/SpacesTest.jl

This gets around issues with resizing a vector if the data is shared

copy vector in `chop`

---

Project.toml

Bump version to v0.6.19

---

.github/workflows/CompatHelper.yml

Copied from https://github.com/JuliaRegistries/CompatHelper.jl/blob/master/.github/workflows/CompatHelper.yml

Update compathelper script

---

.github/workflows/downstream.yml

Initial attempt to include coverage from downstream tests. Let's see if this works.

include downstream coverage

---

Project.toml
src/Fun.jl

Fixes https://github.com/JuliaApproximation/ApproxFun.jl/issues/762.

Suppress wrong broadcasting over x in broadcasteval()

---

src/PDE/KroneckerOperator.jl
src/PDE/PDE.jl

This improves the intermediate inference of the types of `Dx2` and `Dy2`

improve type inference in laplacian

---

Project.toml
src/Operators/general/algebra.jl

This might lead to better inference in simple cases.

Parameterize operators in `PlusOperator`/`TimesOperator`

---

Project.toml
src/Multivariate/TensorSpace.jl

Fix https://github.com/JuliaApproximation/ApproxFun.jl/issues/770

avoid casting in transform

---

Project.toml

Version bump to v0.7.23

---

src/show.jl
test/show.jl

After this,
```julia
julia> Chebyshev() ⊕ Chebyshev()
Chebyshev() ⊕ Chebyshev()
```

Add space while displaying a sum space

---

Project.toml
src/Operators/general/algebra.jl
src/PDE/KroneckerOperator.jl
src/PDE/PDE.jl

After this,
```julia
julia> f = Fun((x,y)->x^2*y^2, Chebyshev()^2);
julia> g = grad(f);
julia> g(0.1, 0.2) ≈ [(2*0.1) * (0.2^2), (0.1^2) * (2*0.2)]
true
```

Fix grad for bivariate `Fun`

---

Project.toml
src/PDE/KroneckerOperator.jl
src/PDE/PDE.jl

After this, the following works:
```julia
julia> P = ProductFun((x,y)->x*y, Chebyshev()^2);
julia> D1 = Derivative(Chebyshev()^2, [1,0]);
julia> x, y = 0.1, 0.2;
julia> ((P * (D1 + Multiplication(Fun()) ⊗ I)) * P)(x, y) ≈ x * y^2 +  x^3 * y^2
true
```

BivariateFun right multiplication by operator

---

Project.toml
src/ApproxFunBase.jl
src/Fun.jl
src/specialfunctions.jl
test/runtests.jl

Also, extend some special functions for `Fun` on constant spaces.

Fix imports of special functions

---

src/ApproxFunBase.jl
src/Domains/PiecewiseSegment.jl
src/Domains/ProductDomain.jl
src/Operators/Operator.jl
src/Operators/general/InterlaceOperator.jl
src/Operators/general/algebra.jl
src/Operators/spacepromotion.jl
src/Operators/systems.jl
src/Spaces/SumSpace.jl

This is often better inferred, as we may specialize common cases.

Use `promote_eltypeof` instead of `mapreduce`

---

Project.toml

Version bump to v0.7.40

---

src/ApproxFunBase.jl
src/Operators/general/InterlaceOperator.jl
src/Operators/spacepromotion.jl
src/Spaces/ProductSpaceOperators.jl

On master
```julia
julia> @btime Derivative(Fourier(), 1);
39.594 μs (260 allocations: 10.50 KiB)
```
This PR
```julia
julia> @btime Derivative(Fourier(), 1);
26.839 μs (206 allocations: 8.72 KiB)
```

views in promotespaces for Matrix

---

Project.toml
src/Multivariate/TensorSpace.jl
src/PDE/KroneckerOperator.jl
test/SpacesTest.jl

After this,
```julia
julia> ApproxFunBase.spacescompatible(Chebyshev()^2, Chebyshev()^2)
true
```

spacescompatible for tensorspace

---

Project.toml

Breaking change in `DomainSets`

Version bump to v0.7.45

---

src/show.jl
test/show.jl

After this,
```julia
julia> Fun(x->[3], ConstantSpace(0..1))
[3] on 0..1
```

show for constant array space

---

src/LinearAlgebra/rowvector.jl

Fewer specialized methods for `RowVector`

---

Project.toml
src/Multivariate/TensorSpace.jl

Separating the function out leads to a significant speedup

Don't use `invoke` in `TensorSpace` iteration

---

Project.toml

Version bump to v0.7.61

---

src/Operators/general/PartialInverseOperator.jl

Also delete the empty `DiagonalOperator` file

Update `PartialInverseOperator` docstring

---

src/Spaces/SumSpace.jl

Reverts JuliaApproximation/ApproxFunBase.jl#385

Revert "specialize components for tuple directsumspace Fun"

---

Project.toml
src/Caching/blockbanded.jl
src/Caching/ragged.jl
src/LinearAlgebra/RaggedMatrix.jl

Mutability doesn't seem to add anything here

Make RaggedMatrix immutable

---

.github/workflows/downstream.yml

Lower optimization in downstream tests

---

Project.toml
src/Operators/Operator.jl
src/Operators/spacepromotion.jl
test/runtests.jl

Fix https://github.com/JuliaApproximation/ApproxFunOrthogonalPolynomials.jl/issues/237. After this
```julia
julia> size(Multiplication(Fun(), Ultraspherical(1)))
(ℵ₀, ℵ₀)
```

Don't forward size to SpaceOperator

---

Project.toml
src/show.jl
test/show.jl

Fixes the show in
```julia
julia> Fun(1, ConstantSpace(Point(3)))
1 on Point(3)
```

show for const Fun on Point

---

.github/workflows/ci.yml
.github/workflows/downstream.yml

This will hopefully address https://github.com/JuliaApproximation/ApproxFunBase.jl/pull/191

Include workflow name in concurrency test

---

src/show.jl
test/show.jl

Fix the display in
```julia
julia> f = Fun(2, ConstantSpace(union(Point(-1), Point(1))))
2 on Point(-1) ∪ Point(1)
```

Fix Fun show on union of Points

---

src/Operators/banded/CalculusOperator.jl

This seems to match the intent (as in the comment that follows). It also provides more freedom to `conversion_type`,

Change `conversion_type` to `hasconversion` in DefaultDerivative/Integral

---

Project.toml
src/Operators/banded/CalculusOperator.jl

Backport: Improve inference in normalized space derivative

---

Project.toml

Fix version, bump to v0.9.15

---

.github/workflows/downstream.yml

Backport https://github.com/JuliaApproximation/ApproxFunBase.jl/pull/619

Backport: Dev ApproxFunBaseTest in downstream tests

---

Project.toml
src/Space.jl

This will reduce failures from the change in the displayed form

Update Space docstrings to not show OneElement explicitly

---

src/ApproxFunBase.jl
src/Fun.jl
src/LinearAlgebra/blas.jl
src/LinearAlgebra/helper.jl
src/LinearAlgebra/hesseneigs.jl
src/LinearAlgebra/rowvector.jl
src/Multivariate/Multivariate.jl
src/Spaces/QuotientSpace.jl

This makes it easier to reason about imports

Move imports to the main file
