Project.toml

This should tag the changes introduced in https://github.com/JuliaApproximation/ApproxFunBase.jl/commit/3fa958b49d87d40c289c29d6c21ea58f9cb1bb8c. I had forgotten to bump the patch version in that PR.

Version bump to v0.5.7

---

Project.toml
src/constructors.jl

Tests are yet to be added, but this allows non-`Function` callable structs to be passed to the `Fun` constructor, such as an interpolation instance. This and makes it easy to e.g. generate a Chebyshev interpolation from a spline interpolation computed using another package.
```julia
julia> using ApproxFun
julia> struct Foo end
julia> (::Foo)(x) = 2
julia> Fun(Foo(), Chebyshev())
Fun(Chebyshev(),[2.0])
```
The current workaround is using 
```julia
Fun(x -> Foo()(x), Chebyshev())
```
which seems redundant.

Accept callables in Fun constructor

---

.github/workflows/ci.yml
.github/workflows/downstream.yml

This tries to automate testing for downstream breakage (ApproxFun.jl) in the CI pipeline. Also, we may skip the CI on trivial changes, such as in the README, that are not automatically tested anyway.

Automatically test for downstream breakage

---

Project.toml
src/ApproxFunBase.jl
src/Fun.jl
test/SpacesTest.jl
test/runtests.jl

Fixes #94 by ensuring that `Base.real` and `ApproxFunBase.real` are separate functions. Tests for `ApproxFun` pass locally with this.

Avoid pirating `Base.real`

---

src/Operators/banded/Multiplication.jl
src/Operators/general/FiniteOperator.jl
src/Operators/general/algebra.jl
test/runtests.jl

This fixes an associativity bug. On master,
```julia
julia> M = Multiplication(Fun());
julia> @btime $M * $M;
2.207 μs (10 allocations: 304 bytes)
julia> TimesOperator([M*M, M]) # this fails
ERROR: MethodError: no method matching Vector{Operator{Float64}}(::Int64)
julia> TimesOperator([M, M*M]) # this works
TimesOperator : ApproxFunBase.UnsetSpace() → ApproxFunBase.UnsetSpace()
julia> M1 = Multiplication(Fun());
julia> M2 = Multiplication(Fun());
julia> M1 == M2
false
```
This PR
```julia
julia> @btime $M * $M;
1.368 μs (16 allocations: 528 bytes)
julia> TimesOperator([M*M, M])
TimesOperator : ApproxFunBase.UnsetSpace() → ApproxFunBase.UnsetSpace()
julia> M1 == M2
true
```

Fix bug in `TimesOperator` constructor, and add Multiplication equality

---

src/Operators/general/algebra.jl
test/runtests.jl

Splitting into function calls helps with performance for badly inferred code.
On master
```julia
julia> d = Derivative(Chebyshev());
julia> @btime reduce(+, fill($d, 100));
5.437 ms (41644 allocations: 989.08 KiB)
```
This PR
```julia
julia> @btime reduce(+, fill($d, 100));
1.895 ms (36793 allocations: 834.39 KiB)
```

Improve `PlusOperator` performance

---

src/Caching/almostbanded.jl
src/Caching/banded.jl
src/Caching/blockbanded.jl
src/Caching/matrix.jl
src/Caching/ragged.jl
src/Domains/Domains.jl
src/Fun.jl
src/LinearAlgebra/RaggedMatrix.jl
src/LinearAlgebra/clenshaw.jl
src/LinearAlgebra/helper.jl
src/LinearAlgebra/standardchop.jl
src/Multivariate/Multivariate.jl
src/Multivariate/TensorSpace.jl
src/Operators/Operator.jl
src/Operators/SubOperator.jl
src/Operators/general/CachedOperator.jl
src/Operators/general/FiniteOperator.jl
src/Operators/general/algebra.jl
src/Operators/nullspace.jl
src/Operators/qr.jl
src/PDE/KroneckerOperator.jl
src/Spaces/ArraySpace.jl
src/Spaces/ConstantSpace.jl
src/Spaces/HeavisideSpace.jl
src/Spaces/ProductSpaceOperators.jl
src/Spaces/SumSpace.jl
src/constructors.jl
src/specialfunctions.jl

Minor stylistic change to replace non-breaking spaces with regular ones. Non-breaking spaces show up as Unicode codes in some text editors, and they may be replaced by regular spaces without any change in functionality. An example of the change, and the way it's displayed in sublime text:
Only white spaces are changed in this PR. I used
```console
find src -type f -name "*.jl" -print0 | xargs -0 sed -i '' -e 's/\xc2\xa0/ /g'
```
to perform a recursive find-replace.

Replace non-breaking spaces with regular ones

---

Project.toml
src/LinearAlgebra/helper.jl
test/runtests.jl

On master
```julia
julia> @btime ApproxFunBase.hasnumargs(x->x, 1)
199.208 ns (2 allocations: 80 bytes)
true
julia> @btime ApproxFunBase.hasnumargs((x,y)->x+y, 2)
234.893 ns (3 allocations: 112 bytes)
true
```
This PR
```julia
julia> @btime ApproxFunBase.hasnumargs(x->x, 1)
57.413 ns (0 allocations: 0 bytes)
true
julia> @btime ApproxFunBase.hasnumargs((x,y)->x+y, 2)
77.941 ns (0 allocations: 0 bytes)
true
```
I've not added a test for zero allocations, as this is often unreliable in my experience in the test environment.

Remove allocations in hasnumargs

---

src/Fun.jl
test/SpacesTest.jl

On master
```julia
julia> f = Fun(x->2, Chebyshev())
Fun(Chebyshev(),[2.0])
julia> @code_typed (f -> oftype(f, Fun(x->2, Chebyshev())))(f)
CodeInfo(
1 ─ %1 = invoke ApproxFunBase.default_Fun(ApproxFunBase.DFunction(var"#16#18"())::ApproxFunBase.DFunction, $(QuoteNode(Chebyshev()))::Chebyshev{ChebyshevInterval{Float64}, Float64})::Any
│   %2 = Main.oftype(f, %1)::Any
└──      return %2
) => Any
```
This PR
```julia
julia> @code_typed (f -> oftype(f, Fun(x->2, Chebyshev())))(f)
CodeInfo(
1 ─ %1 = invoke ApproxFunBase.default_Fun(ApproxFunBase.DFunction(var"#8#10"())::ApproxFunBase.DFunction, $(QuoteNode(Chebyshev()))::Chebyshev{ChebyshevInterval{Float64}, Float64})::Any
│   %2 = Main.oftype(f, %1)::Fun{Chebyshev{ChebyshevInterval{Float64}, Float64}, Float64, Vector{Float64}}
└──      return …
```

Fix convert methods to always return the exact type

---

src/LinearAlgebra/helper.jl
src/constructors.jl
test/SpacesTest.jl

I don't really see a slowdown with this, looking at the test runtimes.
On master (types aren't inferred)
```julia
julia> @time Fun(x->2, Chebyshev()) # first execution
4.478566 seconds (9.03 M allocations: 534.299 MiB, 11.28% gc time, 99.91% compilation time)
Fun(Chebyshev(),[2.0])
julia> @code_typed Fun(x->x, Chebyshev())
CodeInfo(
1 ─ %1 = invoke ApproxFunBase.default_Fun(ApproxFunBase.DFunction(var"#1#2"())::ApproxFunBase.DFunction, d::Chebyshev{ChebyshevInterval{Float64}, Float64})::Any
└──      return %1
) => Any
julia> @btime Fun(x->x, Chebyshev());
21.116 μs (106 allocations: 4.88 KiB)
```
This PR (types are inferred now)
```julia
julia> @time Fun(x->2, Chebyshev()) # first execution
4.586365 seconds (9.21 M allocations: 537.594 MiB, 16.58% gc time, 99.95% compilation time) …
```

Make the `Fun` constructor type-inferrable

---

src/Operators/general/algebra.jl

This provides a minor performance boost, as typed concatenation is type-stable, whereas splatting isn't.
```julia
julia> d = Derivative();
julia> @btime reduce(+, fill($d, 100));
5.354 ms (16399 allocations: 512.64 KiB) # master
5.210 ms (16039 allocations: 428.41 KiB) # PR
```
The idea is
```julia
julia> f(a,b) = Operator{eltype(a)}[a.ops..., b.ops...]
f (generic function with 1 method)
julia> g(a,b) = Operator{eltype(a)}[a.ops; b.ops]
g (generic function with 1 method)
julia> A = reduce(+, fill(d, 100));
julia> f(A, A) == g(A, A)
true
julia> @btime f($A, $A);
4.192 μs (1 allocation: 1.77 KiB)
julia> @btime g($A, $A);
294.360 ns (1 allocation: 1.77 KiB)
```

Avoid splatting in operator sum and multiplication

---

src/ApproxFunBase.jl
src/Caching/almostbanded.jl
src/Caching/banded.jl
src/Caching/blockbanded.jl
src/Caching/matrix.jl
src/Caching/ragged.jl
test/runtests.jl

Currently, `ApproxFunBase.dot` is an alias for `LinearAlgebra.dot`, which makes some of these methods defined here commit type-piracy. This PR solves this.
Problematic methods on master:
https://github.com/JuliaApproximation/ApproxFunBase.jl/blob/eeb33d47aa797b9482e363f53b97241d7a058042/src/LinearAlgebra/helper.jl#L5-L9
Also, since
```julia
julia> @which BandedMatrices.dot
LinearAlgebra
```
these method calls may be replaced by `ApproxFunBase.dot`.

Avoid pirating dot

---

src/Fun.jl
test/SpacesTest.jl

This helps with type inference in `intpow`, although it's not fully inferred because of negative exponents. This provides a minor performance boost.
On master
```julia
julia> f = Fun(x->x, Chebyshev())
Fun(Chebyshev(),[0.0, 1.0])
julia> @btime $f^6;
5.611 μs (45 allocations: 2.42 KiB)
```
this PR
```julia
julia> @btime $f^6;
5.330 μs (52 allocations: 2.61 KiB)
```

avoid recursion in intpow

---

Project.toml
src/Operators/Operator.jl
src/Operators/general/algebra.jl
test/SpacesTest.jl

After this, the following is inferred:
```julia
julia> @inferred Fun() * Derivative()
TimesOperator : ApproxFunBase.UnsetSpace() → ApproxFunBase.UnsetSpace()
```

Improve inference in `Fun * Operator`

---

.github/workflows/downstream.yml
Project.toml
src/Operators/nullspace.jl

Also add downstream test on `v1.6`, which should cover this change.

Restore QR on old julia versions

---

src/Operators/general/algebra.jl

* `_promote_eltypeof(A, B)` as an alias for `promote_type(eltype(A), eltype(B))`

Add `_promote_eltypeof` to simplify operations

---

Project.toml
src/constructors.jl
test/SpacesTest.jl

The 2-argument constructor had earlier been relaxed to accept general callable types. This PR relaxes the 3-argument constructor. After this, something like this works:
```julia
julia> struct Foo end
julia> (::Foo)(x) = rand()
julia> Fun(Foo(), Chebyshev());
```

Relax 3-argument Fun constructor

---

src/Operators/Operator.jl
src/Operators/spacepromotion.jl
test/SpacesTest.jl

After this, the following is type stable:
```julia
julia> M = Multiplication(Fun(PointSpace(1:3), [1:3;]));
julia> v = [M, M];
julia> @inferred ApproxFunBase.promotespaces(v);
```

Type stability in promote spaces

---

src/Operators/Operator.jl
src/Operators/SubOperator.jl
test/runtests.jl

The following works after this:
```julia
julia> D = Dirichlet(ConstantSpace(0..1))
DirichletWrapper : ConstantSpace(0..1) → 2-element ArraySpace:
ConstantSpace{DomainSets.Point{Int64}, Float64}[ConstantSpace(DomainSets.Point{Int64}(0)), ConstantSpace(DomainSets.Point{Int64}(1))]
1.0
1.0
julia> S = D[:, :]
SubOperator : ConstantSpace(0..1)|1:1 → 2-element ArraySpace:
ConstantSpace{DomainSets.Point{Int64}, Float64}[ConstantSpace(DomainSets.Point{Int64}(0)), ConstantSpace(DomainSets.Point{Int64}(1))]|1:2
1.0
1.0
julia> S[:, :]
2×1 BandedMatrix{Float64} with bandwidths (1, 0):
1.0
1.0
julia> S[:, 1]
2-element Vector{Float64}:
1.0
1.0
```

`SubOperator` index with colon

---

src/Operators/banded/Conversion.jl
src/Operators/spacepromotion.jl
src/Space.jl
src/Spaces/ProductSpaceOperators.jl
src/Spaces/Spaces.jl
src/Spaces/SumSpace.jl

Type assertions to functions add an extra conversion at the end. Since conversion to `Any` is a no-op, this make no difference to the result. For example,
```julia
julia> f(x)::Any = x
f (generic function with 1 method)
julia> @code_typed f(2)
CodeInfo(
1 ─     return x
) => Int64
```
We may therefore remove the `::Any` type assertions on functions

remove unnecessary conversion to Any

---

src/Operators/general/algebra.jl
test/SpacesTest.jl

Use the fact that an operator with an infinite bandwidth will have an infinite size as well

size for infinite bandwidth plusoperator

---

Project.toml
src/Operators/banded/Conversion.jl
test/SpacesTest.jl

This makes conversions such as the following work, as conversion to the canonical space is defined:
```julia
julia> Conversion(Chebyshev(), NormalizedPolynomialSpace(Ultraspherical(1)))
ConversionWrapper : Chebyshev() → NormalizedUltraspherical(1)
1.2533141373155001  0.0                 -0.6266570686577501    ⋅                  …    ⋅                    ⋅                    ⋅                    ⋅                  ⋅
⋅                  0.6266570686577501   0.0                 -0.6266570686577501       ⋅                    ⋅                    ⋅                    ⋅                  ⋅
⋅                   ⋅                   0.6266570686577501   0.0                      ⋅                    ⋅                    ⋅                    ⋅                  ⋅
⋅                   ⋅ …
```

Try both `canonicalspace`s in `defaultConversion` 

---

src/Fun.jl
src/Operators/SubOperator.jl
src/Operators/banded/Multiplication.jl
src/Operators/qr.jl
src/Space.jl
src/testing.jl
test/SpacesTest.jl

This improves TTFX somewhat:
master
```julia
julia> f = Fun(Chebyshev(0..1));
julia> @time union(space(f), space(f))
2.642244 seconds (4.15 M allocations: 255.851 MiB, 12.97% gc time, 100.00% compilation time)
Chebyshev(0..1)
```
PR
```julia
julia> @time union(space(f), space(f))
0.066540 seconds (157.41 k allocations: 9.111 MiB, 99.42% compilation time)
Chebyshev(0..1)
```
This isn't really representative of a real use case, though, but I'm trying to look into how to improve badly inferred code paths.
Also split `default_mult` into components to avoid recursion.
Finally, reduce proliferation of type parameters to avoid over specialization.

despecialize union, split default_mult

---

src/Caching/almostbanded.jl

This addresses https://github.com/JuliaApproximation/ApproxFunBase.jl/issues/5
Caching/almostbanded.jl isn't covered by tests, and I'm not sure how to construct an almost banded operator on a DirectSumSpace without using SingularIntegralEquations.jl

Replace `getindex(sp,k)` with `component(sp,k)` in CachedOperator

---

Project.toml
src/Fun.jl
test/SpacesTest.jl

It seems `Fun()` was not being type-inferred. Fixed now.
```julia
julia> @inferred Fun()
```

improve inference in `Fun()`

---

Project.toml
src/Fun.jl
test/SpacesTest.jl

This helps with inference in some common cases
On master
```julia
julia> @inferred (x -> x^2)(Fun())
ERROR: return type Fun{Chebyshev{ChebyshevInterval{Float64}, Float64}, Float64, Vector{Float64}} does not match inferred return type Any
```
This PR
```julia
julia> @inferred (x -> x^2)(Fun())
Fun(Chebyshev(),[0.5, 0.0, 0.5])
```

Specialize `literal_pow` for `Fun`

---

src/LinearAlgebra/standardchop.jl
src/Operators/general/algebra.jl

On master
```julia
julia> f1 = Fun()
julia> @time M1 = Multiplication(f1)
1.115510 seconds (1.94 M allocations: 101.535 MiB, 31.87% gc time, 99.95% compilation time)
ConcreteMultiplication : ApproxFunBase.UnsetSpace() → ApproxFunBase.UnsetSpace()
julia> @time M1 * M1
0.608894 seconds (1.50 M allocations: 87.054 MiB, 6.12% gc time, 99.79% compilation time)
TimesOperator : ApproxFunBase.UnsetSpace() → ApproxFunBase.UnsetSpace()
julia> @code_warntype M1 * M1
[...]
A::ApproxFunBase.ConcreteMultiplication{Chebyshev{ChebyshevInterval{Float64}, Float64}, ApproxFunBase.UnsetSpace, Float64}
B::ApproxFunBase.ConcreteMultiplication{Chebyshev{ChebyshevInterval{Float64}, Float64}, ApproxFunBase.UnsetSpace, Float64}
Body::Operator{Float64}
```
This PR
```julia
julia> @time …
```

improved TTFX in multiplication

---

.github/workflows/ci.yml

Now that `v1` points to `v1.8`

Remove explicit CI test on `v1.8`

---

Project.toml
src/ApproxFunBase.jl
src/Operators/SubOperator.jl
src/Operators/general/OperatorLayout.jl
src/show.jl
test/SpacesTest.jl
test/show.jl

This makes the display of operators similar to that for matrices.
After this
```julia
julia> Derivative(NormalizedChebyshev())
DerivativeWrapper : NormalizedChebyshev() → Ultraspherical(1)
⋅  0.797885   ⋅        ⋅        ⋅        ⋅        ⋅        ⋅        ⋅        ⋅       ⋅
⋅   ⋅        1.59577   ⋅        ⋅        ⋅        ⋅        ⋅        ⋅        ⋅       ⋅
⋅   ⋅         ⋅       2.39365   ⋅        ⋅        ⋅        ⋅        ⋅        ⋅       ⋅
⋅   ⋅         ⋅        ⋅       3.19154   ⋅        ⋅        ⋅        ⋅        ⋅       ⋅
⋅   ⋅         ⋅        ⋅        ⋅       3.98942   ⋅        ⋅        ⋅        ⋅       ⋅
⋅   ⋅         ⋅        ⋅        ⋅        ⋅       4.78731   ⋅        ⋅        ⋅       ⋅
⋅   ⋅         ⋅        ⋅        ⋅        ⋅        ⋅       5.58519   ⋅        ⋅       ⋅
⋅ …
```

compact show for operators

---

Project.toml
src/LinearAlgebra/helper.jl
test/runtests.jl

Try `zero` with the element first, which works for a vector of `Fun`s.
```julia
julia> f = Fun()
julia> pad([f], 3)
3-element Vector{Fun{Chebyshev{ChebyshevInterval{Float64}, Float64}, Float64, Vector{Float64}}}:
Fun(Chebyshev(), [0.0])
Fun(Chebyshev(), [0.0])
```

zero with element instead of eltype in pad

---

src/Operators/banded/Multiplication.jl
test/SpacesTest.jl

Fixes `f*g` where the `eltype`s aren't convertible without inexact errors, such as real and complex `Fun`s. Now 
```julia
julia> f = Fun(Chebyshev(), Float64[1:101;]);
julia> g = Fun(Chebyshev(), Float64[1:100;]*im);
julia> f(0.5)*g(0.5) ≈ (f*g)(0.5)
true
```

multiplication of real and complex Fun

---

.github/workflows/downstream.yml
Project.toml
src/ApproxFunBase.jl
src/Fun.jl
src/onehotvector.jl
test/SpacesTest.jl

This lets one evaluate a basis function at a specific point without allocations
```julia
julia> @btime ApproxFunBase.basisfunction(Chebyshev(), 100_000)(0.4)
167.131 μs (0 allocations: 0 bytes)
-0.4341364613359062
```

add OneHotVector

---

src/Operators/general/algebra.jl
test/runtests.jl

On master
```julia
julia> M = Multiplication(Fun(), Chebyshev())
ConcreteMultiplication : Chebyshev() → Chebyshev()
0.0  0.5   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
1.0  0.0  0.5   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅   0.5  0.0  0.5   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅   0.5  0.0  0.5   ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅    ⋅   0.5  0.0  0.5   ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅    ⋅    ⋅   0.5  0.0  0.5   ⋅    ⋅    ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅   0.5  0.0  0.5   ⋅    ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.5  0.0  0.5   ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.5  0.0  0.5  ⋅
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.5  0.0  ⋱
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋱   ⋱
julia> @code_typed size(M + M)
CodeInfo(
1 ─ %1 = invoke ApproxFunBase._size(A::PlusOperator{Float64, Tuple{Int64, …
```

store size for plus and times operators

---

src/Operators/qr.jl
test/SpacesTest.jl

Adds the missing `ldiv_coefficients!(::Operator, ::AbstractVector)` method by converting the operator to the `eltype` of the vector, and fixes `ldiv_coefficients(::Operator{<:Real}, ::AbstractVector{<:Complex})`.
On master
```julia
julia> v = rand(ComplexF32, 4);
julia> ApproxFunBase.ldiv_coefficients(Conversion(Chebyshev(), Ultraspherical(1)), v)
4-element Vector{ComplexF64}:
1.1584808230400085 + NaN*im
1.2104620933532715 + NaN*im
1.744177222251892 + NaN*im
0.6986570358276367 + NaN*im
julia> ApproxFunBase.ldiv_coefficients!(Conversion(Chebyshev(), Ultraspherical(1)), copy(v))
ERROR: StackOverflowError
```
This PR
```julia
julia> ApproxFunBase.ldiv_coefficients(Conversion(Chebyshev(), Ultraspherical(1)), v)
4-element Vector{ComplexF64}:
1.1584808230400085 + 1.8255538940429688im …
```

bugfix in `ldiv_coefficients`

---

src/LinearAlgebra/RaggedMatrix.jl
test/MatrixTest.jl

On master
```julia
julia> B = ApproxFunBase.brand(4,4,1,1)
4×4 BandedMatrix{Float64} with bandwidths (1, 1):
0.491781  0.491816   ⋅         ⋅ 
0.320611  0.941615  0.309694   ⋅ 
⋅        0.80753   0.90633   0.990165
⋅         ⋅        0.276171  0.920501
julia> R = ApproxFunBase.RaggedMatrix(B)
4×4 ApproxFunBase.RaggedMatrix{Float64}:
0.491781  0.491816  0.0       0.0
0.320611  0.941615  0.309694  0.0
0.0       0.80753   0.90633   0.990165
0.0       0.0       0.276171  0.920501
julia> similar(R, ComplexF64)
ERROR: MethodError: no method matching Vector{ComplexF64}(::Int64)
```
This PR
```julia
julia> similar(R, ComplexF64)
4×4 ApproxFunBase.RaggedMatrix{ComplexF64}:
0.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im
0.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im
0.0+0.0im  0.0+0.0im  0.0+0.0im …
```

Fix `similar` for `RaggedMatrix`

---

src/Caching/matrix.jl
src/LinearAlgebra/helper.jl
src/Operators/general/CachedOperator.jl
test/SpacesTest.jl

Specialize `promotedomainspace` and `promoterangespace` for a `CachedOperator`, preserving the caching nature. Also, some bug-fixes in array initialization.
After this,
```julia
julia> cache(Derivative()) : Chebyshev()
CachedOperator : Chebyshev() → Ultraspherical(1)
⋅  1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅   ⋅   2.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅   ⋅    ⋅   3.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅   ⋅    ⋅    ⋅   4.0   ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅   ⋅    ⋅    ⋅    ⋅   5.0   ⋅    ⋅    ⋅    ⋅   ⋅
⋅   ⋅    ⋅    ⋅    ⋅    ⋅   6.0   ⋅    ⋅    ⋅   ⋅
⋅   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   7.0   ⋅    ⋅   ⋅
⋅   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   8.0   ⋅   ⋅
⋅   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   9.0  ⋅
⋅   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋱
⋅   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ …
```

domain promotion for cached operator

---

src/LinearAlgebra/rowvector.jl
test/runtests.jl

Modernize the constructors, and remove explicit indexing methods (fallback implementations should be fast enough). Also fixes concatenation etc.

Fix `RowVector` methods

---

Project.toml
src/Fun.jl
src/Multivariate/VectorFun.jl
test/SpacesTest.jl

For some reason, constant propagation isn't working here, so explicitly defining the function helps with inference.
On master
```julia
julia> @code_warntype norm(Fun())
MethodInstance for LinearAlgebra.norm(::Fun{Chebyshev{ChebyshevInterval{Float64}, Float64}, Float64, Vector{Float64}})
from norm(f::Fun) in ApproxFunBase at /home/jb6888/Dropbox/JuliaPackages/ApproxFunBase/src/Fun.jl:415
Arguments
#self#::Core.Const(LinearAlgebra.norm)
f::Fun{Chebyshev{ChebyshevInterval{Float64}, Float64}, Float64, Vector{Float64}}
Body::Any
1 ─ %1 = ApproxFunBase.norm(f, 2)::Any
└──      return %1
```
This PR
```julia
julia> @code_warntype norm(Fun())
MethodInstance for LinearAlgebra.norm(::Fun{Chebyshev{ChebyshevInterval{Float64}, Float64}, Float64, Vector{Float64}})
from norm(f::Fun) in ApproxFunBase at …
```

Improve inference in `norm`

---

Project.toml
src/ApproxFunBase.jl
src/Operators/spacepromotion.jl
src/Spaces/SumSpace.jl
test/SpacesTest.jl

On master
```julia
julia> f = Fun(PointSpace(1:3), 1:3)
Fun(PointSpace([1, 2, 3]), 1:3)
julia> @btime $f.^2;
10.658 μs (108 allocations: 5.23 KiB)
julia> A = Derivative(Chebyshev());
julia> B = Derivative(Ultraspherical(1));
julia> @btime ApproxFunBase.promotespaces($A,$B);
3.033 μs (37 allocations: 1.37 KiB)
```
This PR
```julia
julia> @btime $f.^2;
9.863 μs (105 allocations: 5.14 KiB)
julia> @btime ApproxFunBase.promotespaces($A,$B);
911.275 ns (23 allocations: 936 bytes)
```

Function barrier in PiecewiseSpace

---

Project.toml
src/specialfunctions.jl
test/SpacesTest.jl

This makes `ℯ^x` redirect to `exp(x)` for `x::Fun`
Fixes https://github.com/JuliaApproximation/ApproxFun.jl/issues/434

Support euler exponentiation

---

Project.toml
src/Domain.jl
src/Fun.jl
src/Multivariate/TensorSpace.jl
test/runtests.jl

After this, the following are type-inferred on Julia v1.8:
```julia
julia> @inferred (() -> Chebyshev()^2)()
Chebyshev()⊗Chebyshev()
julia> y = @inferred Fun() + Fun(ChebyshevInterval{BigFloat}())
Fun(Chebyshev(), BigFloat[0.0, 2.0])
```
Tests to be added to `ApproxFunOrthogonalPolynomials`.

improve inference in literal exponentiation

---

Project.toml
src/Multivariate/TensorSpace.jl
src/Spaces/ArraySpace.jl
test/SpacesTest.jl

This helps with inference:
```julia
julia> @inferred (() -> Chebyshev()^2)()
Chebyshev()⊗Chebyshev()
julia> @inferred (() -> Chebyshev()^3)()
Chebyshev()⊗Chebyshev()⊗Chebyshev()
julia> @inferred (() -> Chebyshev(0..1)^3)()
Chebyshev(0..1)⊗Chebyshev(0..1)⊗Chebyshev(0..1)
```
Also fixes `one(f)` for `Fun`s on `ArraySpace`s:
```julia
julia> f = Fun(x->[x, x], -1..1)
Fun(2-element ArraySpace:
Chebyshev{IntervalSets.ClosedInterval{Int64}, Float64}[Chebyshev(-1..1), Chebyshev(-1..1)], [0.0, 0.0, 1.0, 1.0])
julia> f + one(f)
Fun(2-element ArraySpace:
Chebyshev{IntervalSets.ClosedInterval{Int64}, Float64}[Chebyshev(-1..1), Chebyshev(-1..1)], [1.0, 1.0, 1.0, 1.0])
```

improve inference in space tensor product

---

Project.toml
src/Fun.jl
src/Operators/banded/Multiplication.jl

After this, the following is inferred:
```julia
julia> function f()
x = Fun(0..1)
x^2
end
f (generic function with 2 methods)
julia> @inferred f()
Fun(Chebyshev(0..1), [0.375, 0.5, 0.125])
```

improve inference in Fun multiplication

---

src/Fun.jl

This simplifies branches in code where the exponent isn't a literal constant
```julia
julia> f = Fun(0..1)
Fun(Chebyshev(0..1), [0.5, 0.5])
julia> function g(f)
n = 2
f^n
end
```
On master:
```julia
julia> @code_typed g(f)
CodeInfo(
1 ─ %1 = π (2, Int64)
│   %2 = invoke ApproxFunOrthogonalPolynomials.intpow(f::Function, %1::Int64)::Any
└──      return %2
) => Any
```
This PR
```julia
julia> @code_typed g(f)
CodeInfo(
1 ─ %1 = invoke ApproxFunBase.default_mult(f::Fun{Chebyshev{IntervalSets.ClosedInterval{Int64}, Float64}, Float64, Vector{Float64}}, f::Fun{Chebyshev{IntervalSets.ClosedInterval{Int64}, Float64}, Float64, Vector{Float64}})::Any
└──      return %1
) => Any
```

aggressive constprop in intpow

---

Project.toml
src/Fun.jl

This makes the following type-stable:
```julia
julia> @inferred Fun() + 1
Fun(Chebyshev(), [1.0, 1.0])
```

promote in (::Fun) + (::Number)

---

src/Operators/general/algebra.jl

Use concrete `eltype`s in the intermediate matrices

Improve inference in `BlockBandedMatrix` conversion

---

Project.toml
src/Fun.jl
src/Multivariate/TensorSpace.jl

This completes the partially implemented 2D and adds nD transforms, based on Kronecker products of grids.
After this,
```julia
julia> x = Fun(); y = Fun()^2;
julia> M = values(x) .* values(y)'
2×3 Matrix{Float64}:
0.53033   0.0   0.53033
-0.53033  -0.0  -0.53033
julia> C = transform(Chebyshev() ⊗ Chebyshev(), M)
2×3 Matrix{Float64}:
0.0  0.0          0.0
0.5  7.40149e-17  0.5
julia> C ≈ coefficients(x) .* coefficients(y)'
true
julia> itransform(Chebyshev() ⊗ Chebyshev(), C) ≈ M
true
julia> x = Fun(); y = Fun()^2; z = Fun()^3;
julia> M = values(x) .* values(y)' .* reshape(values(z), 1, 1, :);
julia> C = transform(Chebyshev() ⊗ Chebyshev() ⊗ Chebyshev(), M);
julia> C ≈ coefficients(x) .* coefficients(y)' .* reshape(coefficients(z), 1,1,:)
true
```

n-d transforms

---

Project.toml
src/Multivariate/TensorSpace.jl

`maximum` with `init` isn't defined on v1.5, so this PR works around it.

`reduce(max` instead of `maximum`

---

Project.toml
src/Multivariate/LowRankFun.jl
src/Multivariate/Multivariate.jl
src/Multivariate/ProductFun.jl

After this
```julia
julia> f = (x,y)->x^2 * y^3
#983 (generic function with 1 method)
julia> L = LowRankFun(f, Chebyshev() ⊗ Chebyshev())
LowRankFun on Chebyshev()⊗Chebyshev() of rank 1.
julia> (L^2)(0.1, 0.2) ≈ (L * L)(0.1, 0.2)
true
julia> P = ProductFun(f, Chebyshev()⊗Chebyshev())
ProductFun on Chebyshev()⊗Chebyshev()
julia> (L * P)(0.1, 0.2) ≈ (P * L)(0.1, 0.2) ≈ (L^2)(0.1, 0.2)
true
```

Fix multiplication of `MultivariateFun`

---

src/show.jl
test/show.jl

This improves the display of tensor spaces using certain fonts, while being mildly inconvenient in others. This also helps with tab-completion in the REPL, which seems to only work with the extra spaces present.
Before
```julia
julia> Chebyshev() ⊗ Chebyshev()
Chebyshev()⊗Chebyshev()
```
After
```julia
julia> Chebyshev() ⊗ Chebyshev()
Chebyshev() ⊗ Chebyshev()
```

Add extra spaces while displaying a `TensorSpace`

---

Project.toml
src/Multivariate/TensorSpace.jl

This fixes
```julia
julia> f(x,y) = x*y
f (generic function with 1 method)
julia> L = LowRankFun(f, Chebyshev() ⊗ Chebyshev())
LowRankFun on Chebyshev() ⊗ Chebyshev() of rank 1.
julia> F = Fun(L)
Fun(Chebyshev() ⊗ Chebyshev(), [0.0, 0.0, 0.0, 0.0, 1.0])
julia> L(0.1, 0.2) ≈ F(0.1, 0.2)
true
```

All coeffs in `fromtensor`

---

Project.toml
src/Multivariate/LowRankFun.jl

This makes the `LowRankFun` constructor fully type-inferrable:
```julia
julia> @inferred LowRankFun((x,y) -> exp(x) * cos(y))
LowRankFun on Chebyshev() ⊗ Chebyshev() of rank 1.
```

improve inference in LowRankFun

---

src/Operators/SubOperator.jl

Since domain and range spaces might be poorly inferred, introducing a function barrier might provide some performance improvements.
```julia
julia> dx=0..1; dt=0.0..0.001
0.0..0.001
julia> C=Conversion(Chebyshev(dx)*Ultraspherical(1,dt),Ultraspherical(2,dx)*Ultraspherical(1,dt));
julia> @time C[Block.(1:4),Block.(1:4)];
5.071718 seconds (12.10 M allocations: 614.771 MiB, 5.35% gc time, 99.93% compilation time)
```
Second run performance
```julia
julia> @time C[Block.(1:4),Block.(1:4)];
0.000195 seconds (97 allocations: 8.078 KiB) # master
0.000105 seconds (91 allocations: 7.922 KiB) # PR
```

function barrier in SubOperator

---

Project.toml
src/ApproxFunBase.jl
src/testing.jl

The idea is to move testing convenience functions to a separate package, one that may be imported downstream. This way, `ApproxFunBase` doesn't need to depend on `Test`. This PR is the first step that resolve namespace issues. Next, downstream packages need to be updated to import testing functions from `ApproxFunBaseTest` instead of from `ApproxFunBase`.

move tests to a separate module

---

src/testing.jl

This should not be necessary, as the individual test routines are imported downstream.

Don't export `ApproxFunBaseTest`

---

Project.toml
src/Multivariate/Multivariate.jl
src/Multivariate/ProductFun.jl
src/PDE/KroneckerOperator.jl
src/PDE/PDE.jl
src/Space.jl

Specialize the action of certain operators using the structures of `LowRankFun` or `ProductFun`, instead of casting everything to `Fun` first

Kronecker operator acting on `LowRankFun`/`ProductFun`

---

src/PDE/KroneckerOperator.jl
src/PDE/PDE.jl

This slightly improves inference in certain operator constructions. The type parameter `S` in wrapper ops seems to not be linked to anything, so I'm not sure what tests to add for this.

improve in inference in mulvar ops

---

Project.toml
src/PDE/PDE.jl

Fix `grad(f)` to make the following consistent:
```julia
julia> f = Fun((x,y)->x^2*y^2, Chebyshev()^2);
julia> grad(f) == grad(space(f)) * f
true
```
TBH the fix should be in the other direction, with `grad(space(f)) * f` returning a `Fun`, so I'm uncertain if this PR is the right direction.

make `grad` consistent

---

Project.toml
src/Operators/general/OperatorFunction.jl
test/SpacesTest.jl

After this PR
```julia
julia> A = 2I : Chebyshev()
ConstantOperator : Chebyshev() → Chebyshev()
2    ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅
⋅  2    ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅
⋅   ⋅  2    ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅
⋅   ⋅   ⋅  2    ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋅
⋅   ⋅   ⋅   ⋅  2    ⋅   ⋅   ⋅   ⋅   ⋅  ⋅
⋅   ⋅   ⋅   ⋅   ⋅  2    ⋅   ⋅   ⋅   ⋅  ⋅
⋅   ⋅   ⋅   ⋅   ⋅   ⋅  2    ⋅   ⋅   ⋅  ⋅
⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  2    ⋅   ⋅  ⋅
⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  2    ⋅  ⋅
⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  2   ⋅
⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  ⋱
julia> inv(A)
ConcreteOperatorFunction : Chebyshev() → Chebyshev()
0.5   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅   0.5   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅   0.5   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅    ⋅   0.5   ⋅    ⋅ …
```

Fix convert for ConcreteOperatorFunction

---

src/show.jl
test/show.jl

Avoid using `T.name.name` when `nameof` does exactly that

Use `nameof` in show

---

src/onehotvector.jl
src/specialfunctions.jl

Change usage such as `strictconvert(T, x)::T` to `strictconvert(T, x)`

Clean up `strictconvert` usage

---

Project.toml
src/Multivariate/Multivariate.jl
src/Operators/banded/CalculusOperator.jl

Move methods like `dot` and `cross` for `∇` over to this package.

Move calculus functions from `ApproxFun`

---

Project.toml
src/Operators/general/InterlaceOperator.jl

This helps marginally with type-stability
On master
```julia
julia> @code_warntype [Derivative(); Dirichlet()]
MethodInstance for vcat(::ApproxFunBase.ConcreteDerivative{ApproxFunBase.UnsetSpace, Int64, ApproxFunBase.UnsetNumber}, ::ApproxFunBase.DirichletWrapper{ApproxFunBase.InterlaceOperator{ApproxFunBase.UnsetNumber, 1, ApproxFunBase.UnsetSpace, ApproxFunBase.ArraySpace{ApproxFunBase.UnsetSpace, 1, ApproxFunBase.AnyDomain, ApproxFunBase.UnsetNumber}, ApproxFunBase.CachedIterator{Tuple{Int64, Int64}, ApproxFunBase.BlockInterlacer{Tuple{FillArrays.Ones{Int64, 1, Tuple{InfiniteArrays.OneToInf{Int64}}}}}}, ApproxFunBase.CachedIterator{Tuple{Int64, Int64}, ApproxFunBase.BlockInterlacer{Tuple{FillArrays.Ones{Int64, 1, Tuple{InfiniteArrays.OneToInf{Int64}}}, FillArrays.Ones{Int64, 1, …
```

Tuples in _vcat

---

src/Operators/general/InterlaceOperator.jl
src/Operators/spacepromotion.jl
test/runtests.jl

After this, the following are equivalent:
```julia
julia> M = Multiplication(Fun())
ConcreteMultiplication : ApproxFunBase.UnsetSpace() → ApproxFunBase.UnsetSpace()
julia> ApproxFunBase.promotespaces([M,M])
2-element Vector{Operator{Float64}}:
ConcreteMultiplication : ApproxFunBase.UnsetSpace() → ApproxFunBase.UnsetSpace()
ConcreteMultiplication : ApproxFunBase.UnsetSpace() → ApproxFunBase.UnsetSpace()
julia> ApproxFunBase.promotespaces((M,M))
2-element Vector{Operator{Float64}}:
ConcreteMultiplication : ApproxFunBase.UnsetSpace() → ApproxFunBase.UnsetSpace()
ConcreteMultiplication : ApproxFunBase.UnsetSpace() → ApproxFunBase.UnsetSpace()
```

Tuples in promotespaces

---

src/Operators/Operator.jl
src/Operators/general/InterlaceOperator.jl
src/Operators/spacepromotion.jl
src/Spaces/ArraySpace.jl
src/Spaces/ProductSpaceOperators.jl

Among other things, this makes operations such as the following type-stable:
```julia
julia> @inferred (() -> Dirichlet(Chebyshev(), 2))()
DirichletWrapper : Chebyshev() → 2-element ArraySpace:
ConstantSpace{DomainSets.Point{Float64}, Float64}[ConstantSpace(Point(-1.0)), ConstantSpace(Point(1.0))]
0.0  0.0  4.0  -24.0  80.0  -200.0  420.0  -784.0  1344.0  -2160.0  ⋯
0.0  0.0  4.0   24.0  80.0   200.0  420.0   784.0  1344.0   2160.0  ⋯
```

Propagate `Tuple`s in `InterlaceOperator`

---

Project.toml
src/Operators/functionals/Evaluation.jl
src/Operators/general/InterlaceOperator.jl

Inference in often terrible in `promotedomainspace`, so we may choose to skip this in cases where the domain doesn't need to be promoted. After this, the following is type-stable:
```julia
julia> @inferred (r -> Dirichlet(r, 1))(Chebyshev(-1..1))
DirichletWrapper : Chebyshev(-1..1) → 2-element ArraySpace:
ConstantSpace{DomainSets.Point{Int64}, Float64}[ConstantSpace(Point(-1)), ConstantSpace(Point(1))]
0.0  1.0  -4.0  9.0  -16.0  25.0  -36.0  49.0  -64.0  81.0  ⋯
0.0  1.0   4.0  9.0   16.0  25.0   36.0  49.0   64.0  81.0  ⋯
```

Optionally skip InterlaceOp domain promote

---

Project.toml
src/Multivariate/TensorSpace.jl
test/SpacesTest.jl

Using `mapreduce` to determine type parameters suffers from inference issues at times, so we may avoid this in some common (1D and 2D) cases.

Improve `TensorSpace` inference

---

src/PDE/KroneckerOperator.jl

This improves inference in `Multiplication(f::Fun{<:TensorSpace}, S::TensorSpace)`, as `+(ops...)` can be poorly inferred.

PlusOp in TensorSpace Multiplication

---

src/Domain.jl
src/Domains/ProductDomain.jl
src/Domains/Segment.jl
src/Domains/multivariate.jl
src/Fun.jl
src/LinearAlgebra/helper.jl
src/Multivariate/TensorSpace.jl
src/Operators/spacepromotion.jl
src/PDE/KroneckerOperator.jl
src/PDE/PDE.jl
src/Space.jl
src/Spaces/ArraySpace.jl
src/Spaces/ConstantSpace.jl
src/Spaces/SubSpace.jl
src/constructors.jl
test/SpacesTest.jl

While the alias `Vec` is convenient, it's easy to confuse `Vec` with `Vector`. Explicitly spelling out `SVector` avoids this.

Use `SVector` instead of `Vec`

---

src/Domains/PiecewiseSegment.jl
src/Domains/multivariate.jl
src/Spaces/HeavisideSpace.jl

After this,
```julia
julia> dx = dy = ChebyshevInterval()
-1.0..1.0 (Chebyshev)
julia> using LinearAlgebra
julia> d = dx × dy
(-1.0..1.0 (Chebyshev)) × (-1.0..1.0 (Chebyshev))
julia> ∂(d)
PiecewiseSegment{StaticArraysCore.SVector{2, Float64}, StaticArraysCore.SVector{5, StaticArraysCore.SVector{2, Float64}}}(StaticArraysCore.SVector{2, Float64}[[-1.0, -1.0], [1.0, -1.0], [1.0, 1.0], [-1.0, 1.0], [-1.0, -1.0]])
```

Support SVector in PiecewiseSegment

---

Project.toml
src/Operators/general/algebra.jl
test/runtests.jl

This uses a Tuple of operators internally instead of a Vector, which helps improve type inference.
```julia
julia> D = Derivative(Chebyshev(0..1));
julia> @btime $D + $D;
5.558 μs (45 allocations: 2.09 KiB) # master
2.119 μs (19 allocations: 1008 bytes) # PR
julia> M = Multiplication(Fun(Chebyshev(0..1)), Chebyshev(0..1));
julia> @btime $D + $M;
8.598 μs (73 allocations: 3.38 KiB) # master
3.840 μs (37 allocations: 1.88 KiB) # PR
```
After this PR, the following is fully inferred:
```julia
julia> @inferred (() -> (D = Derivative(Chebyshev(0..1)); D + D))()
PlusOperator : Chebyshev(0..1) → Ultraspherical(1,0..1)
⋅  4.0   ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅   ⋅
⋅   ⋅   8.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅   ⋅
⋅   ⋅    ⋅   12.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅   ⋅
⋅   ⋅ …
```

Improve inference in PlusOperator

---

src/Operators/general/algebra.jl

On master
```julia
julia> D = Derivative(Chebyshev(0..1));
julia> @code_warntype (D -> eltype(D + D))(D)
MethodInstance for (::var"#333#334")(::ApproxFunBase.ConcreteDerivative{Chebyshev{IntervalSets.ClosedInterval{Int64}, Float64}, Int64, Float64})
from (::var"#333#334")(D) in Main at REPL[24]:1
Arguments
#self#::Core.Const(var"#333#334"())
D::ApproxFunBase.ConcreteDerivative{Chebyshev{IntervalSets.ClosedInterval{Int64}, Float64}, Int64, Float64}
Body::Any
1 ─ %1 = (D + D)::PlusOperator{_A, _B, Tuple{Infinities.InfiniteCardinal{0}, Infinities.InfiniteCardinal{0}}, _C} where {_A, _B, _C<:Operator{_A}}
│   %2 = Main.eltype(%1)::Any
└──      return %2
```
This PR
```julia
julia> @code_warntype (D -> eltype(D + D))(D)
MethodInstance for …
```

Pass eltype to PlusOperator

---

src/Operators/general/algebra.jl

This makes the following fully inferrable, with a corresponding change in `ApproxFunOrthogonalPolynomials`:
```julia
julia> @inferred (() -> Fun() * Derivative(Chebyshev()))()
TimesOperator : Chebyshev() → Ultraspherical(1)
0.0  0.0  1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅   0.5  0.0  1.5   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅   1.0  0.0  2.0   ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅    ⋅   1.5  0.0  2.5   ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅    ⋅    ⋅   2.0  0.0  3.0   ⋅    ⋅    ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅   2.5  0.0  3.5   ⋅    ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅    ⋅   3.0  0.0  4.0   ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   3.5  0.0  4.5  ⋅
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   4.0  0.0  ⋱
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   4.5  ⋱
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋱
```

Aggressive constprop in Fun * Operator

---

Project.toml
src/Operators/functionals/Evaluation.jl
src/show.jl

Fix #286 partly. After this,
```julia
julia> f = Fun(x -> Float64[1, 2])
Fun(2-element ArraySpace:
[Chebyshev(), Chebyshev()], [1.0, 2.0])
julia> Evaluation(0.5)*f
[1.0, 2.0] on Point(0.5)
```

Fix evaluation for arrayspace

---

src/Operators/functionals/Evaluation.jl

Address some concerns from #286 
After this, `Evaluation` at endpoint works as expected:
```julia
julia> f = Fun(x -> Float64[1, 2])
Fun(2-element ArraySpace:
[Chebyshev(), Chebyshev()], [1.0, 2.0])
julia> Evaluation(1) * f
[1.0, 2.0] on Point(1.0)
```

`Evaluate` for `ArraySpace` at endpoints

---

src/Multivariate/ProductFun.jl

After this
```julia
julia> F = Fun((x,y) ->x^2, Chebyshev()^2)
Fun(Chebyshev() ⊗ Chebyshev(), [0.5, 0.0, 0.0, 0.0, 0.0, 0.5])
julia> ProductFun(F) |> coefficients
3×1 Matrix{Float64}:
0.5
0.0
0.5
```
Trailing zero columns along the second dimension are trimmed.

Trim trailing zeros in ProductFun(::Fun)

---

Project.toml
src/Operators/general/algebra.jl
test/runtests.jl

In this PR, we assume that a `PlusOperator` or a `TimesOperator` wraps a `Vector{Operator{T}}` only if the components are incompatible, so the result of the `convert` may recreate the container for type-stability.

Retain `Vector{Operator{T}}` in `convert`

---

src/Operators/general/algebra.jl
test/runtests.jl

This PR uses the fact that indexing a `TimesOperator` using `UnitRange`s is fast, so when indexing using `AbstractRange`s, we may instead index using `UnitRange`s, and index into the result with the original indices provided.
On master
```julia
julia> M = Multiplication(Fun(x -> x^10, Chebyshev()), Chebyshev());
julia> T = M * M;
julia> @btime $T[1:2:20, 1:2:20];
269.429 μs (1003 allocations: 306.94 KiB)
```
This PR
```julia
julia> @btime $T[1:2:20, 1:2:20];
28.857 μs (13 allocations: 22.33 KiB)
```

Optimized `TimesOperator` `AbstractRange` indexing

---

Project.toml
src/Spaces/ArraySpace.jl

On master
```julia
julia> sp = ApproxFunBase.ArraySpace(fill(Chebyshev(),2))
2-element ArraySpace:
[Chebyshev(), Chebyshev()]
julia> @btime ApproxFunBase.interlacer($sp);
405.720 ns (0 allocations: 0 bytes)
```
This PR
```julia
julia> @btime ApproxFunBase.interlacer($sp);
230.925 ns (0 allocations: 0 bytes)
```

Speed up BlockInterlacer

---

Project.toml
src/ApproxFunBase.jl
src/Operators/banded/CalculusOperator.jl
src/Operators/general/InterlaceOperator.jl
src/Spaces/ProductSpaceOperators.jl

Passing `StaticInt`s as derivative orders helps with type inference. This PR also removes some splatting in constructing vectors.

Numbers as derivative orders

---

Project.toml
src/Domain.jl

We may break early while comparing intervals in `domainscompatible` if the endpoints differ, even if the closedness is different.

domainscompatible for different closedness

---

Project.toml
src/ApproxFunBase.jl
src/Domains/Domains.jl
src/Domains/ProductDomain.jl
src/Multivariate/TensorSpace.jl
src/PDE/KroneckerOperator.jl
test/SpacesTest.jl

Also, don't overwrite `DomainSets` functions such as `factors`.

Don't import deprecated `DomainSets` functions

---

Project.toml
src/Operators/banded/Conversion.jl
src/Operators/general/algebra.jl
src/PDE/KroneckerOperator.jl
test/runtests.jl

Bugfix, as `A_mul_B` isn't defined for all operators. This should only be used in specific cases.

don't use A_mul_B in kron multiplication

---

src/Multivariate/TensorSpace.jl

On master
```julia
julia> f3 = Fun(Chebyshev()^3, rand(100));
julia> @btime $f3(0.1, 0.1, 0.1);
146.563 μs (1869 allocations: 98.86 KiB)
```
This PR
```julia
julia> @btime $f3(0.1, 0.1, 0.1);
21.280 μs (563 allocations: 37.64 KiB)
```
cc @benjione

Fix boxing in TrivialTensorizer next

---

src/Multivariate/TensorSpace.jl

This provides a performance boost
On master
```julia
julia> f3 = Fun(Chebyshev()^3, rand(1000));
julia> @btime $f3(0.1, 0.1, 0.1);
219.015 μs (5133 allocations: 390.56 KiB)
```
This PR
```julia
julia> @btime $f3(0.1, 0.1, 0.1);
175.871 μs (4132 allocations: 312.36 KiB)
```
Currently, iterating over `MultiExponents` is expensive, as it allocates an array in each iteration. Since the size of the array is constant, the allocation may be moved to the constructor.

Static vector in `Tensorizer` next

---

src/Operators/banded/CalculusOperator.jl
src/constructors.jl

This reduces type-piracy in that package

Move `Fun(::Interval)` constructor from AFOP

---

ApproxFunBaseTest/Project.toml
ApproxFunBaseTest/src/ApproxFunBaseTest.jl

Compare matrices instead of `BandedMatrix` instances, which is often faster from a TTFX viewpoint

Compare matrices in backend_testinfoperator

---

.github/workflows/downstream.yml

Julia v1.6 seems to be buggy, as some tests for `ApproxFunOrthogonalPolynomials` fail with O0 and O1 but work with O2 (floating-point precision changes with optimization level). This doesn't happen for other versions (1.8 and above). I'm reverting the optimization level to the default (O2) for now, but in the future, perhaps we can have a more granular optimization setting.

revert optimization level in downstream

---

Project.toml
src/Multivariate/Multivariate.jl
src/Operators/general/algebra.jl
src/Space.jl

Compute `isbandedblockbanded` and `israggedbelow` in the constructor, to avoid repeated dynamic dispatch.

Add flags to PlusOperator and TimesOperator

---

src/Operators/Operator.jl
src/PDE/KroneckerOperator.jl

After this,
```julia
julia> C = Conversion(Chebyshev()*Legendre(), Chebyshev()*Legendre())
ConversionWrapper : Chebyshev() ⊗ Legendre() → Chebyshev() ⊗ Legendre()
1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ⋯
0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ⋱
0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ⋱
0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ⋱
0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ⋱
0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ⋱
0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ⋱
0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ⋱
0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ⋱
0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ⋱
⋮    ⋱    ⋱    ⋱    ⋱    ⋱    ⋱    ⋱    ⋱    ⋱   ⋱
julia> using LinearAlgebra
julia> isdiag(C)
true
```
On master …

Specialize `isdiag` for `KroneckerOperator`

---

src/PDE/KroneckerOperator.jl

This means that diagonal conversions won't become `RaggedMatrix`es:
```julia
julia> C = Conversion(Chebyshev()*Legendre(), Chebyshev()*NormalizedLegendre())
ConversionWrapper : Chebyshev() ⊗ Legendre() → Chebyshev() ⊗ NormalizedLegendre()
1.41421   ⋅         ⋅        ⋅         ⋅         ⋅        ⋅         ⋅         ⋅         ⋅       ⋅
⋅       0.816497   ⋅        ⋅         ⋅         ⋅        ⋅         ⋅         ⋅         ⋅       ⋅
⋅        ⋅        1.41421   ⋅         ⋅         ⋅        ⋅         ⋅         ⋅         ⋅       ⋅
⋅        ⋅         ⋅       0.632456   ⋅         ⋅        ⋅         ⋅         ⋅         ⋅       ⋅
⋅        ⋅         ⋅        ⋅        0.816497   ⋅        ⋅         ⋅         ⋅         ⋅       ⋅
⋅        ⋅         ⋅        ⋅         ⋅        1.41421   ⋅         ⋅ …
```

Diagonal `KroneckerOperator` has zero bandwidth

---

Project.toml
src/Spaces/SumSpace.jl

After this,
```julia
julia> s = Fourier()
Fourier(【0.0,6.283185307179586❫)
julia> @inferred ApproxFunBase.block(s, 2)
Block(1)
```

mapreduce to map+reduce for tuples

---

src/Multivariate/TensorSpace.jl
test/SpacesTest.jl

After this, the following is type-stable:
```julia
julia> @inferred (x -> x^2)(Chebyshev(0..1))
Chebyshev(0..1) ⊗ Chebyshev(0..1)
```

constant propagation in `Space` power

---

Project.toml
src/Multivariate/TensorSpace.jl

After this,
```julia
julia> f = Fun();
julia> P = ProductFun([f, f, f], space(f));
julia> typeof(domain(P)) == ApproxFunBase.domaintype(space(P))
true
```

ProductSpace domain type fix

---

src/LinearAlgebra/helper.jl

On master
```julia
julia> s = Fourier();
julia> b = ApproxFunBase.BlockInterlacer(s);
julia> @btime first($b, 10);
6.564 μs (124 allocations: 6.95 KiB)
```
This PR
```julia
julia> @btime first($b, 10);
1.103 μs (28 allocations: 2.31 KiB)
```

Improve inference in blockintercer iteration

---

src/LinearAlgebra/helper.jl

This might help with type-inference on older versions of Julia

=== in comparing with nothing

---

Project.toml
src/Operators/SubOperator.jl
test/runtests.jl

Using `bandwidths(A::Operator)` directly instead of `bandwidth(A,1), bandwidth(A,2)` helps with type inference.
Tests are a bit unfortunate, as the exact types need to be specified in `@inferred`.

`Bandwidths` tuple in view

---

src/Space.jl
test/SpacesTest.jl

Fix https://github.com/JuliaApproximation/ApproxFun.jl/issues/827. After this,
```julia
Chebyshev()(n)
```
returns the n-th Chebyshev polynomial.
The result may be evaluated as 
```julia
julia> Chebyshev()(2, 0.1)
-0.98
```

Make spaces callable

---

src/show.jl

On master
```julia
julia> f = Fun((x,y) -> x^2*y^2, Chebyshev()^2)
Fun(Chebyshev() ⊗ Chebyshev(), [0.25, 0.0, -4.0571552518292214e-17, 0.25, 0.0, 0.24999999999999994, 0.0, -5.001914895543676e-17, 0.0, -1.0316031908487694e-17, -3.271192840413408e-17, 0.0, 0.24999999999999994])
```
This PR
```julia
julia> f = Fun((x,y) -> x^2*y^2, Chebyshev()^2)
Fun(Chebyshev() ⊗ Chebyshev(), [0.25, 0.0, -4.05716e-17, 0.25, 0.0, 0.25, 0.0, -5.00191e-17, 0.0, -1.0316e-17, -3.27119e-17, 0.0, 0.25])
```

compact coefficient show for `Fun`

---

src/ApproxFunBase.jl
src/Caching/almostbanded.jl
src/Caching/banded.jl
src/Caching/bandedblockbanded.jl
src/Caching/blockbanded.jl
src/Caching/matrix.jl
src/Caching/ragged.jl
src/LinearAlgebra/RaggedMatrix.jl
src/Operators/Operator.jl
src/Operators/general/InterlaceOperator.jl
src/Operators/general/algebra.jl

On Julia v1.9, `LinearAlgebra.axpy! !== BLAS.axpy!`
In most cases, we should be calling `LinearAlgebra.axpy!` instead of `BLAS.axpy!`, as there may not be a BLAS call involved in the function. Internally, `LinearAlgebra.axpy!` calls `BLAS.axpy!` wherever appropriate.

Use `LinearAlgbera.axpy!` uniformly

---

Project.toml
src/LinearAlgebra/helper.jl
src/Multivariate/TensorSpace.jl

On master
```julia
julia> t = ApproxFunBase.tensorizer(Chebyshev()^2);
julia> @btime first(ApproxFunBase.cache($t), 100);
26.686 μs (702 allocations: 58.25 KiB)
```
This PR
```julia
julia> @btime first(ApproxFunBase.cache($t), 100);
16.425 μs (502 allocations: 47.31 KiB)
```

Type-stability in 2d tensorizer iteration

---

src/Operators/general/InterlaceOperator.jl
src/Operators/general/algebra.jl
src/Operators/spacepromotion.jl

This improves type inference by some extent, as the result may be inferrable. This is an internal method, so the change should be ok.

Disable empty vector in findmindomain/findmaxrange

---

src/Operators/SubOperator.jl
src/Operators/general/InterlaceOperator.jl
src/Operators/general/algebra.jl
src/Operators/spacepromotion.jl

This improves performance slightly
On master
```julia
julia> D = Derivative(Chebyshev()) ⊗ Derivative(Chebyshev());
julia> D2 = D[Fun((x,y) -> x^2*y^2, Chebyshev()^2)];
julia> DBv = view(D2, Block(1):Block(20), Block(1):Block(20));
julia> @btime BandedBlockBandedMatrix(Zeros, $DBv);
6.338 μs (16 allocations: 104.77 KiB)
```
This PR
```julia
julia> @btime BandedBlockBandedMatrix(Zeros, $DBv);
5.513 μs (11 allocations: 104.23 KiB)
```

BandedBlockBandedMatrix function barrier

---

Project.toml
src/Operators/Operator.jl
src/Operators/banded/CalculusOperator.jl

Also, simplify code generation in the various wrapper macros

Conditionally forward domain to wrapper op

---

ApproxFunBaseTest/Project.toml
Project.toml
src/Operators/Operator.jl
src/Operators/banded/CalculusOperator.jl
src/Operators/banded/Conversion.jl
src/Operators/banded/Multiplication.jl
src/Operators/functionals/Evaluation.jl
src/Operators/general/algebra.jl
src/PDE/KroneckerOperator.jl
src/PDE/PDE.jl

With this, the following becomes type-inferred:
```julia
julia> @inferred (() -> domain(Evaluation(Chebyshev() + Ultraspherical(1), 0.1)))()
-1.0..1.0 (Chebyshev)
```

Spaces in Conversion, Multiplication and Evaluation wrapper

---

src/LinearAlgebra/RaggedMatrix.jl
src/Operators/Operator.jl
src/Operators/banded/ToeplitzOperator.jl
src/Operators/general/InterlaceOperator.jl
src/Operators/general/PartialInverseOperator.jl
src/PDE/KroneckerOperator.jl
src/Spaces/QuotientSpace.jl

Purely stylistic change to replace `Tuple{UnitRange{Int},UnitRange{Int}}` by `NTuple{2,UnitRange{Int}}`

use NTuple{2,UnitRange{Int}}

---

Project.toml
src/Multivariate/LowRankFun.jl

These functions just require the vector to support indexing, so it doesn't need to be a `Vector`

AbstractVector points in `findapproxmaxvector` and friends

---

Project.toml
src/Caching/banded.jl
src/Caching/bandedblockbanded.jl
src/Caching/blockbanded.jl

With this, the following (among others) becomes a small union:
```julia
julia> C = Conversion(Chebyshev(), Ultraspherical(1.0));
julia> @code_warntype ApproxFunBase.CachedOperator(BandedMatrix, C, padding=false)
MethodInstance for Core.kwcall(::NamedTuple{(:padding,), Tuple{Bool}}, ::Type{ApproxFunBase.CachedOperator}, ::Type{BandedMatrix}, ::ApproxFunBase.ConcreteConversion{Chebyshev{ChebyshevInterval{Float64}, Float64}, Ultraspherical{Float64, ChebyshevInterval{Float64}, Float64}, Float64})
from kwcall(::Any, ::Type{ApproxFunBase.CachedOperator}, ::Type{BandedMatrix}, op::Operator) @ ApproxFunBase ~/Dropbox/JuliaPackages/ApproxFunBase/src/Caching/banded.jl:1
Arguments
_::Core.Const(Core.kwcall)
@_2::NamedTuple{(:padding,), Tuple{Bool}}
@_3::Type{ApproxFunBase.CachedOperator} …
```

improve type inference in caching

---

src/Spaces/ProductSpaceOperators.jl

The constant propgation part from https://github.com/JuliaApproximation/ApproxFunBase.jl/pull/401

Constant propagation in `Sumspace`/`Piecewisespace` deriv

---

src/Caching/almostbanded.jl
src/LinearAlgebra/AlmostBandedMatrix.jl
test/runtests.jl

Fix
```julia
julia> @inferred (B -> B.bands)(ApproxFunBase.AlmostBandedMatrix{Float64}(Zeros(4,4), (1,1), 2))
ERROR: return type BandedMatrices.BandedMatrix{Float64, Matrix{Float64}, Base.OneTo{Int64}} does not match inferred return type BandedMatrices.BandedMatrix{Float64}
Stacktrace:
[1] error(s::String)
@ Base ./error.jl:35
[2] top-level scope
@ REPL[9]:1
```

parameterize almostbandedmatrix

---

Project.toml
src/LinearAlgebra/helper.jl
src/Spaces/Spaces.jl
test/runtests.jl

Fix a bug in `interlace` if the spaces have multiple components. In that case, the coefficients need to be interlaced block-wise.
After this, and a corresponding fix to `ApproxFunFourier`, the following works:
```julia
julia> f = Fun(θ->1+cos(θ), Fourier())
Fun(Fourier(【0.0,6.283185307179586❫), [1.0, 1.02893e-16, 1.0])
julia> g = integrate(f)
Fun(CosSpace(【0.0,6.283185307179586❫) ⊕ Chebyshev(0.0..6.283185307179586) ⊕ SinSpace(【0.0,6.283185307179586❫), [0.0, 3.14159, 1.0, -1.02893e-16, 3.14159])
julia> g(0.4) ≈ 0.4 + sin(0.4)
true
```

interlace coefficients by blocks

---

src/LinearAlgebra/RaggedMatrix.jl

```julia
julia> A = rand(500,500);
julia> @btime ApproxFunBase.RaggedMatrix{Float64}($A, $(collect(axes(A,2))));
245.704 μs (6 allocations: 990.83 KiB) # master
135.100 μs (6 allocations: 990.83 KiB) # PR
```

safer inbounds in RaggedMatrix

---

Project.toml
src/Operators/general/algebra.jl

Also, propagate constants aggressively in the TimesOperator constructor. This makes the following type-stable:
```julia
julia> x = Fun();
julia> Σ = DefiniteIntegral(Chebyshev());
julia> @inferred ((x,Σ) -> x*Σ[x])(x,Σ);
```

store isafunctional in TimesOperator

---

Project.toml
src/Operators/functionals/Evaluation.jl
test/runtests.jl

This lets one define `Evaluation` operators using the `enum`
```julia
julia> ApproxFunBase.LeftEndPoint
LeftEndPoint::Boundary = -1
julia> ApproxFunBase.RightEndPoint
RightEndPoint::Boundary = 1
```
This doesn't permit dispatch on the endpoint, but that's often unnecessary. On the other hand, using these will help with type-inference.
Also, some other changes in `getindex` and `rangespace` to make the methods less prone to ambiguities.

boundary enum in Evaluation

---

Project.toml
src/Operators/general/algebra.jl

After this, the following works:
```julia
julia> X = Multiplication(Fun(Legendre()), NormalizedLegendre()) → Jacobi(2,2)
TimesOperator : NormalizedLegendre() → Jacobi(2,2)
0.0       0.174964  0.0          -0.178174    0.0         0.0507621    ⋅           ⋅           ⋅           ⋅         ⋅
0.235702  0.0       3.15416e-17   0.0        -0.149992    0.0         0.0594291    ⋅           ⋅           ⋅         ⋅
⋅        0.174964  0.0          -0.0364447   0.0        -0.140572    0.0         0.067029     ⋅           ⋅         ⋅
⋅         ⋅        0.158114      0.0        -0.0543928   0.0        -0.137281    0.0         0.0738763    ⋅         ⋅
⋅         ⋅         ⋅            0.151178    0.0        -0.0663291   0.0        -0.136687    0.0         0.0801565  ⋅
⋅         ⋅         ⋅             ⋅ …
```

Fix space promotion in timesoperator

---

src/Operators/general/algebra.jl

This makes the following type-inferred:
```julia
julia> @inferred (Derivative() ⊗ I) * Fun((x,y) ->x*y, Chebyshev()^2)
Fun(Ultraspherical(1) ⊗ Chebyshev(), [-2.05209e-17, 1.0, 0.0])
```

improve type-inference in mul_coefficients

---

Project.toml
src/Operators/functionals/CalculusFunctional.jl

After this,
```julia
julia> DefiniteIntegral() * Fun(x->x^2, NormalizedChebyshev())
0.6666666666666665 anywhere
```
matches
```julia
julia> DefiniteIntegral() * Fun(x->x^2, Chebyshev())
0.6666666666666667 anywhere
```

Fix spaces in DefiniteIntegral

---

src/show.jl

This preserves the structured display style of the parent. After this
```julia
julia> Derivative(Chebyshev()) ⊗ Derivative(Chebyshev())
KroneckerOperator : Chebyshev() ⊗ Chebyshev() → Ultraspherical(1) ⊗ Ultraspherical(1)
⋅    ⋅    ⋅   0.0  1.0  0.0  0.0  0.0  0.0  0.0  ⋯
⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.0  2.0  0.0  0.0  ⋱
⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.0  0.0  2.0  0.0  ⋱
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋱
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋱
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋱
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋱
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋱
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋱
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋱
⋮    ⋱    ⋱    ⋱    ⋱    ⋱    ⋱    ⋱    ⋱    ⋱   ⋱
```
The …

Wrap matrix in `show` for `Operator`s

---

Project.toml
src/Operators/banded/ConstantOperator.jl
test/runtests.jl

This provides a performance boost, and will be much faster once `BandedMatrices` is patched.
```julia
julia> Cop = Operator(1.0I) : Chebyshev();
julia> @btime $Cop[1:100, 1:100];
554.956 ns (2 allocations: 944 bytes) # PR
620.203 ns (2 allocations: 944 bytes) # master
```

BandedMatrix for view of ConstantOperator

---

Project.toml
src/Operators/general/algebra.jl
test/runtests.jl

These often show up in operations in normalized polynomial spaces, so it's worth improving the type-inference here.
```julia
julia> @inferred Multiplication(Fun(), NormalizedChebyshev())
MultiplicationWrapper : NormalizedChebyshev() → NormalizedChebyshev()
0.0       0.707107   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
0.707107  0.0       0.5   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅        0.5       0.0  0.5   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅         ⋅        0.5  0.0  0.5   ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅         ⋅         ⋅   0.5  0.0  0.5   ⋅    ⋅    ⋅    ⋅   ⋅
⋅         ⋅         ⋅    ⋅   0.5  0.0  0.5   ⋅    ⋅    ⋅   ⋅
⋅         ⋅         ⋅    ⋅    ⋅   0.5  0.0  0.5   ⋅    ⋅   ⋅
⋅         ⋅         ⋅    ⋅    ⋅    ⋅   0.5  0.0  0.5   ⋅   ⋅
⋅         ⋅         ⋅    ⋅    ⋅    ⋅    ⋅   0.5  0.0 …
```

three-term multiplication involving conversions

---

src/Operators/SubOperator.jl
src/Operators/banded/ConstantOperator.jl
src/Operators/general/algebra.jl
src/Operators/ldiv.jl
src/Operators/qr.jl

This fixes a somewhat serious bug, albeit one that might not be frequently encountered (no wonder it lurked undetected)
On master:
```julia
julia> v = rand(4);
julia> R = Conversion(Chebyshev(), Legendre());
julia> ApproxFunBase.mul_coefficients!(R, copy(v))
4-element Vector{Float64}:
0.0
0.0
0.0
0.0
```
After this PR
```julia
julia> ApproxFunBase.mul_coefficients!(R, copy(v))
4-element Vector{Float64}:
0.41517303921077103
0.17527749035532603
0.7202004312320129
1.35520616568446
julia> ApproxFunBase.mul_coefficients!(R, copy(v)) == ApproxFunBase.mul_coefficients(R, v)
true
```

don't use `mul!` inplace

---

src/Operators/Operator.jl
src/Operators/SubOperator.jl
test/runtests.jl

After this,
```julia
julia> mul_coefficients(view(Conversion(Chebyshev(), Legendre()), 1:3, 1:2), Float64[1,2])
3-element Vector{Float64}:
1.0
1.9999999999999998
0.0
```

Fix mul_coefficients for wrapper types

---

src/Operators/general/algebra.jl
test/runtests.jl

After this,
```julia
julia> S = NormalizedUltraspherical(NormalizedLegendre())
NormalizedUltraspherical(1/2)
julia> r = Fun(S)
Fun(NormalizedUltraspherical(1/2), [0.0, 0.816497])
julia> @inferred (r -> r^2)(r)
Fun(NormalizedUltraspherical(1/2), [0.471405, 0.0, 0.421637])
```

Improve type-inference in `TimesOperator * Fun`

---

src/Operators/Operator.jl

Instead of defining methods for every combination of Integer and vector indices, we may determine the number of dimensions in the result and dispatch to more generic methods.

Orthogonalize `defaultgetindex`

---

Project.toml
src/Operators/functionals/Evaluation.jl

Fixes
```julia
julia> Evaluation(JacobiWeight(0,0,Chebyshev()), 0.5)[1:4]
4-element Vector{Float64}:
1.0
0.5
-0.5
-1.0
```

Fix indexing ConcreteEvaluation with AbstractRange

---

src/ApproxFunBase.jl
src/Operators/Operator.jl
src/Operators/banded/CalculusOperator.jl
src/Operators/banded/ConstantOperator.jl
src/Operators/functionals/CalculusFunctional.jl
src/Operators/functionals/Evaluation.jl
src/Operators/spacepromotion.jl

The goal is to move wrapper structures, wrapped indexing and similar properties to traits. This vastly reduces the number of methods that we need to define.

traits in size/bandwidths in wrapperstructure

---

Project.toml
test/AFOP/Chebyshev/Chebyshev.jl
test/AFOP/Chebyshev/ChebyshevOperators.jl
test/AFOP/Jacobi/Jacobi.jl
test/AFOP/Jacobi/JacobiOperators.jl
test/AFOP/Jacobi/jacobitransform.jl
test/AFOP/PolynomialSpaces.jl
test/AFOP/Ultraspherical/Ultraspherical.jl
test/AFOP/Ultraspherical/UltrasphericalOperators.jl
test/AFOP/Ultraspherical/fastops.jl
test/AFOP/Ultraspherical/ultrasphericalconversions.jl
test/PolynomialSpacesTests.jl
test/runtests.jl

This copies over some of the Polynomial space functionality from `ApproxFunOrthogonalPolynomials`, which makes adding tests easier for this package.

Add tests for `Polynomial` spaces

---

src/ApproxFunBase.jl

Some of these functions are being imported from `Base` and not `SpecialFunctions`, so it's best to be clear about the namespace.

Clean up `SpecialFunctions` imports

---

Project.toml
src/Multivariate/Multivariate.jl
src/PDE/KroneckerOperator.jl
test/PolynomialSpacesTests.jl

After this,
```julia
julia> Fun() ⊗ I
KroneckerOperator : ApproxFunBase.UnsetSpace() ⊗ ApproxFunBase.UnsetSpace() → ApproxFunBase.UnsetSpace() ⊗ ApproxFunBase.UnsetSpace()
```
The `I` is promoted to an operator automatically.

Kron for Fun and UniformScaling

---

Project.toml
src/Operators/general/algebra.jl
test/PolynomialSpacesTests.jl

Also, retain the `Conversion` operators while multiplying `TimesOperator`s, which helps with consistency.

rowstart for PlusOp/TimesOp for InfiniteCardinal

---

src/LinearAlgebra/helper.jl
src/Operators/general/InterlaceOperator.jl
test/runtests.jl
test/show.jl

On master
```julia
julia> B = ApproxFunBase.interlacer(Fourier())
ApproxFunBase.BlockInterlacer((Ones(ℵ₀), Ones(ℵ₀)))
julia> @btime ApproxFunBase.cache($B)[1:100];
19.937 μs (503 allocations: 40.66 KiB)
julia> f = Fun(Chebyshev(0..1) + Chebyshev(1..2))
Fun(Chebyshev(0..1) ⨄ Chebyshev(1..2), [0.5, 1.5, 0.5, 0.5])
julia> @btime Derivative() * $f;
7.413 μs (128 allocations: 7.98 KiB)
```
This PR
```julia
julia> @btime ApproxFunBase.cache($B)[1:100];
1.685 ns (0 allocations: 0 bytes)
julia> @btime Derivative() * $f;
3.285 μs (60 allocations: 4.44 KiB)
```

Don't cache TrivialInterlacer

---

Project.toml
src/Operators/SubOperator.jl

This avoids recursion in the `RaggedMatrix` constructor from `SubOperator`s.
After this,
```julia
julia> d1, r1 = Legendre(), Jacobi(2,2);
julia> d2, r2 = Chebyshev(), Chebyshev();
julia> K = (Operator(I, d1) ⊗ Operator(I, d2)) → (r1 ⊗ r2)
KroneckerOperator : Legendre() ⊗ Chebyshev() → Jacobi(2,2) ⊗ Chebyshev()
1.0  0.0  0.0       0.0  0.0       -0.285714  0.0  0.0        0.0        0.0       ⋯
⋅   1.0  0.0       0.0  0.0        0.0       0.0  0.0       -0.285714   0.0       ⋱
⋅   0.0  0.333333  0.0  0.0        0.0       0.0  0.0        0.0       -0.222222  ⋱
⋅    ⋅    ⋅        1.0  0.0        0.0       0.0  0.0        0.0        0.0       ⋱
⋅    ⋅    ⋅        0.0  0.333333   0.0       0.0  0.0        0.0        0.0       ⋱
⋅    ⋅    ⋅        0.0  0.0        0.214286  0.0  0.0        0.0 …
```

Impove type inference in RaggedMatrix constructor

---

Project.toml
src/Operators/SubOperator.jl

Backport https://github.com/JuliaApproximation/ApproxFunBase.jl/pull/520 to v0.8

Backport v0.8: Impove type inference in RaggedMatrix constructor

---

Project.toml
src/Operators/Operator.jl

The following is type-inferred after this:
```julia
julia> d1, r1 = Legendre(), Jacobi(2,2);
julia> d2, r2 = Chebyshev(), Chebyshev();
julia> K = (Operator(I, d1) ⊗ Operator(I, d2)) → (r1 ⊗ r2);
julia> @inferred BandedBlockBandedMatrix(view(K, Block(1):Block(2), Block(1):Block(2)))
2×2-blocked 3×3 BandedBlockBandedMatrix{Float64, BlockArrays.PseudoBlockMatrix{Float64, Matrix{Float64}, Tuple{BlockArrays.BlockedUnitRange{Vector{Int64}}, BlockArrays.BlockedUnitRange{Vector{Int64}}}}, BlockArrays.BlockedUnitRange{Vector{Int64}}}:
1.0  │  0.0  0.0     
─────┼───────────────
⋅   │  1.0  0.0     
⋅   │   ⋅   0.333333
```

Improve inference in axpy for non-inferred operator

---

src/Operators/SubOperator.jl

This avoids recursion, and improves performance slightly.
Master:
```julia
julia> @btime $K[1:1, 1:1]
38.339 μs (168 allocations: 10.23 KiB)
1×1 ApproxFunBase.RaggedMatrix{Float64}:
1.0
```
PR:
```julia
julia> @btime $K[1:1, 1:1]
37.967 μs (166 allocations: 9.97 KiB)
1×1 ApproxFunBase.RaggedMatrix{Float64}:
1.0
```

Call BandedBlockBandedMatrix directly in SubOperator RaggedMatrix

---

Project.toml
src/Operators/banded/CalculusOperator.jl

After this, the following is type-inferred:
```julia
julia> D = @inferred (S -> Derivative(S, 2))(NormalizedLegendre(0..1))
DerivativeWrapper : NormalizedLegendre(0 .. 1) → Jacobi(2,2,0 .. 1)
⋅    ⋅   26.8328    ⋅       ⋅      ⋅        ⋅        ⋅        ⋅       ⋅     ⋅
⋅    ⋅     ⋅      52.915    ⋅      ⋅        ⋅        ⋅        ⋅       ⋅     ⋅
⋅    ⋅     ⋅        ⋅     90.0     ⋅        ⋅        ⋅        ⋅       ⋅     ⋅
⋅    ⋅     ⋅        ⋅       ⋅   139.298     ⋅        ⋅        ⋅       ⋅     ⋅
⋅    ⋅     ⋅        ⋅       ⋅      ⋅     201.911     ⋅        ⋅       ⋅     ⋅
⋅    ⋅     ⋅        ⋅       ⋅      ⋅        ⋅     278.855     ⋅       ⋅     ⋅
⋅    ⋅     ⋅        ⋅       ⋅      ⋅        ⋅        ⋅     371.08     ⋅     ⋅
⋅    ⋅     ⋅        ⋅       ⋅      ⋅        ⋅        ⋅ …
```

Improve inference in normalized space derivative

---

src/Spaces/QuotientSpace.jl
src/eigen.jl

```julia
ω = 25.0
d = -10..10;
S = Legendre(d);
V = Fun(x -> ω * x^2 + x^4, S)
L = -Derivative(S, 2) + V;
B = Dirichlet(S);
SE = ApproxFun.SymmetricEigensystem(L, B);
```
Using this,
```julia
julia> @btime ApproxFunBase.bandmatrices_eigen($SE, 100);
3.108 ms (6871 allocations: 1.50 MiB) # master
3.027 ms (6427 allocations: 1.48 MiB) # PR
```

Reduce allocations in symmetric eigen

---

Project.toml
src/Multivariate/ProductFun.jl

After this, the following works:
```julia
julia> P = ProductFun((x,y) -> x*y, Chebyshev()^2)
ProductFun on Chebyshev() ⊗ Chebyshev()
julia> coefficients(P, space(P))
2×2 Matrix{Float64}:
0.0  0.0
0.0  1.0
```

Fix coefficients for ProductFun

---

Project.toml
src/Operators/banded/Conversion.jl

After this, the following works:
```julia
julia> Conversion(Chebyshev(), Ultraspherical(1)) : Ultraspherical(1)
ConversionWrapper : Ultraspherical(1) → Ultraspherical(1)
1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅   1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅   1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅    ⋅   1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅    ⋅    ⋅   1.0   ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅   1.0   ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅    ⋅   1.0   ⋅    ⋅    ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   1.0   ⋅    ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   1.0   ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   1.0  ⋅
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋱
```

Promote rangespace/domainspace of Conversion

---

src/Multivariate/ProductFun.jl
src/Multivariate/TensorSpace.jl
test/show.jl

After this,
```julia
julia> P = ProductFun((x,y) -> x*y, Chebyshev()^2)
ProductFun on Chebyshev() ⊗ Chebyshev()
julia> Q = (Derivative() ⊗ I) * P
ProductFun on Ultraspherical(1) ⊗ Chebyshev()
```

TensorSpace in ProductFun constructor

---

Project.toml
src/Multivariate/ProductFun.jl

This makes the following work:
```julia
julia> ProductFun(Fun((x,y)->x*y, Chebyshev()^2), Chebyshev()^2)
ProductFun on Chebyshev() ⊗ Chebyshev()
```

Fix ProductFun constructor ambiguity

---

src/Multivariate/TensorSpace.jl
test/show.jl

After this,
```julia
julia> ApproxFunBase.tensorizer(Chebyshev()^2)
ApproxFunBase.Tensorizer((Ones(ℵ₀), Ones(ℵ₀)))
```
vs master
```julia
julia> ApproxFunBase.tensorizer(Chebyshev()^2)
ApproxFunBase.Tensorizer{Tuple{FillArrays.Ones{Int64, 1, Tuple{InfiniteArrays.OneToInf{Int64}}}, FillArrays.Ones{Int64, 1, Tuple{InfiniteArrays.OneToInf{Int64}}}}}((Ones(ℵ₀), Ones(ℵ₀)))
```
Also, restricts `Tensorizer` to tuples of `AbstractVector{Int}`.

Show for `Tensorizer`

---

src/Spaces/SubSpace.jl

```julia
julia> @btime ApproxFunBase.blocklengths(Chebyshev()|(4:10));
361.251 ns (11 allocations: 416 bytes) # master
293.383 ns (7 allocations: 288 bytes) # PR
```
Using `Zeros` instead of `zeros` reduces allocations.

Reduce allocations in blocklengths

---

src/Spaces/SubSpace.jl

Since `SubSpace` supports arbitrary indices, the constructor may also accept these.

Allow arbitrary indices in SubSpace

---

Project.toml
src/Operators/SubOperator.jl

Instead of `length(b)`, we use `size(b,1)`, which allows trailing dimensions.

Check size in mul_coefficients

---

src/show.jl
test/show.jl

This removes the show method for `Fun{<:Union{ConstantSpace, ArraySpace{<:ConstantSpace}}}`, as the special cases were becoming unwieldy to maintain
Fixes the display for
```julia
julia> D2 = Dirichlet(Chebyshev(),1);
julia> D2 * Fun()
Fun(ApproxFunBase.ArraySpace(ConstantSpace{Point{Float64}, Float64}[ConstantSpace(Point(-1.0)), ConstantSpace(Point(1.0))]), [1.0])
```

Fix show for Fun in an ArraySpace

---

src/Operators/general/InterlaceOperator.jl

After this,
```julia
julia> C = [Dirichlet(Chebyshev()); Dirichlet(Chebyshev(),1)];
julia> Q = QuotientSpace(Chebyshev(), C);
julia> Z = Conversion(Q, Chebyshev());
julia> isapprox((C * Z)[:, 1:5], C[:,1:9] * Z[1:9, 1:5], atol=1e-14)
true
```

Fix bandwidth for InterlaceOperator

---

src/Operators/general/InterlaceOperator.jl

After this, `Dirichlet` boundary conditions may be represented using static vectors of concrete `Operator` types:
```julia
julia> Dirichlet(Chebyshev(),2).op.ops
2-element StaticArraysCore.SVector{2, ApproxFunBase.ConcreteEvaluation{Chebyshev{ChebyshevInterval{Float64}, Float64}, ApproxFunBase.Boundary, Int64, Float64}} with indices SOneTo(2):
ConcreteEvaluation : Chebyshev() → ConstantSpace(Point(-1.0))
ConcreteEvaluation : Chebyshev() → ConstantSpace(Point(1.0))
```

Parameterize array in InterlaceOperator

---

Project.toml
src/Spaces/SumSpace.jl

Fix https://github.com/JuliaApproximation/ApproxFun.jl/issues/905
After this,
```julia
julia> x = Fun()
julia> cumsum(sign(x))
Fun(Chebyshev(the segment [-1.0,-0.0]) ⨄ Chebyshev(the segment [-0.0,1.0]), [-0.5, -0.5, -0.5, 0.5])
```

Fix cumsum for piecewise spaces

---

Project.toml
ext/ApproxFunBaseStatisticsExt.jl
src/ApproxFunBase.jl
test/runtests.jl

Reverts JuliaApproximation/ApproxFunBase.jl#566

Revert "Move Statistics to an extension"

---

Project.toml
src/specialfunctions.jl

Fix https://github.com/JuliaApproximation/ApproxFun.jl/issues/907
After this,
```julia
julia> x = Fun()
julia> a = abs(x)
Fun(ContinuousSpace{Float64, Float64, PiecewiseSegment{Float64, Vector{Float64}}}(PiecewiseSegment{Float64, Vector{Float64}}([-1.0, -0.0, 1.0])), [1.0, 5.55112e-17, 1.0])
julia> using LinearAlgebra
julia> norm(x - a, Inf)
2.0
julia> norm(a - x, Inf)
2.0
```

Fix `maximum(abs, ::Fun)`

---

Project.toml
src/Domain.jl
src/show.jl

After this,
```julia
julia> 𝑪(0..0.5, 0)
-1.0
julia> 𝑪(0..0.5, 0.5)
1.0
```
This is quite a useful operation, and it's helpful to have a shortcut. The plan is to use this in displaying spaces where the variable needs to be mapped to the canonical domain.
Suggestions for a better symbol are welcome. I have picked this arbitrarily, thinking that it's unlikely to clash with other packages.
Also, this changes the displayed form for `Segment` to make it round-trippable.
```julia
julia> Segment(0, 1)
Segment(0.0, 1.0)
```

Export `\biC` as an alias for `tocanonical`

---

Project.toml
src/Operators/banded/Multiplication.jl
src/Operators/general/algebra.jl

This makes the following type-inferred:
```julia
julia> M = Multiplication(Fun(),Chebyshev());
julia> @inferred M * M * M
TimesOperator : Chebyshev() → Chebyshev()
0.0   0.375  0.0    0.125   ⋅      ⋅      ⋅      ⋅      ⋅      ⋅     ⋅
0.75  0.0    0.5    0.0    0.125   ⋅      ⋅      ⋅      ⋅      ⋅     ⋅
0.0   0.5    0.0    0.375  0.0    0.125   ⋅      ⋅      ⋅      ⋅     ⋅
0.25  0.0    0.375  0.0    0.375  0.0    0.125   ⋅      ⋅      ⋅     ⋅
⋅    0.125  0.0    0.375  0.0    0.375  0.0    0.125   ⋅      ⋅     ⋅
⋅     ⋅     0.125  0.0    0.375  0.0    0.375  0.0    0.125   ⋅     ⋅
⋅     ⋅      ⋅     0.125  0.0    0.375  0.0    0.375  0.0    0.125  ⋅
⋅     ⋅      ⋅      ⋅     0.125  0.0    0.375  0.0    0.375  0.0    ⋱
⋅     ⋅      ⋅      ⋅      ⋅     0.125  0.0    0.375  0.0    0.375  ⋱
⋅ …
```

Improve type-inference in multiplying with TimesOperator

---

Project.toml
src/Fun.jl
test/SpacesTest.jl

This allows one to write type-stable exponentiation, using an unsigned exponent

isnegative in intpow

---

src/Operators/banded/ConstantOperator.jl

This should make `iszeroop` an operation that works on types, and not values, which would help with type-inference

Don't treat ConstantOperator as a zeroop

---

Project.toml
src/Spaces/ConstantSpace.jl
test/SpacesTest.jl

I have implemented the `integrate` and `differentiate` methods for `ConstantSpace`. This addition was motivated to add support for taking the norm of ConstantSpace functionals. I have also added a test for the norm operation.

Implement calculus operations for ConstantSpace

---

Project.toml
src/Spaces/ConstantSpace.jl
src/show.jl
test/SpacesTest.jl
test/show.jl

After this, the following works (the `Fun` has an empty coefficient vector):
```julia
julia> C = Multiplication(Fun(ConstantSpace(), Float64[]), ConstantSpace())
ConcreteMultiplication : ConstantSpace → ConstantSpace
0.0
```

Fix ConstantSpace Multiplication for empty coefficients

---

Project.toml
src/Multivariate/TensorSpace.jl
test/SpacesTest.jl

Fix #602
After this,
```julia
julia> S = Chebyshev(1..2)⊗Chebyshev(3..4)
Chebyshev(1 .. 2) ⊗ Chebyshev(3 .. 4)
julia> [p ∈ domain(factor(S, 1)) for p in points(S, 10, 10)[1]]
10×10 Matrix{Bool}:
1  1  1  1  1  1  1  1  1  1
1  1  1  1  1  1  1  1  1  1
1  1  1  1  1  1  1  1  1  1
1  1  1  1  1  1  1  1  1  1
1  1  1  1  1  1  1  1  1  1
1  1  1  1  1  1  1  1  1  1
1  1  1  1  1  1  1  1  1  1
1  1  1  1  1  1  1  1  1  1
1  1  1  1  1  1  1  1  1  1
1  1  1  1  1  1  1  1  1  1
julia> [p ∈ domain(factor(S, 2)) for p in points(S, 10, 10)[2]]
10×10 Matrix{Bool}:
1  1  1  1  1  1  1  1  1  1
1  1  1  1  1  1  1  1  1  1
1  1  1  1  1  1  1  1  1  1
1  1  1  1  1  1  1  1  1  1
1  1  1  1  1  1  1  1  1  1
1  1  1  1  1  1  1  1  1  1
1  1  1  1  1  1  1  1  1  1
1  1  1  1  1  1  1  1  1 …
```

Remove fromcanonical in points for BivariateSpace

---

src/Operators/functionals/Evaluation.jl

for `(l|r)(diffbc|dirichlet|neumann)`,  `ivp`, `bvp` and `periodic`

add a few docstrings

---

.github/workflows/downstream.yml

This had been disabled owing to a bug in Pkg, which has since been fixed.

Dev ApproxFunBaseTest in downstream tests

---

src/constructors.jl

Small bugfix, just missing a type parameter in `zeros`.
Before this PR:
```julia
julia> using ApproxFunBase, ApproxFun
julia> @code_warntype Fun(exp, Chebyshev(big(-1.0) .. big(1.0)))
MethodInstance for Fun(::typeof(exp), ::Chebyshev{IntervalSets.ClosedInterval{BigFloat}, BigFloat})
from Fun(f, d::Space) @ ApproxFunBase ~/.julia/dev/ApproxFunBase/src/constructors.jl:225
Arguments
#self#::Type{Fun}
f::Core.Const(exp)
d::Chebyshev{IntervalSets.ClosedInterval{BigFloat}, BigFloat}
Body::Union{Fun{Chebyshev{IntervalSets.ClosedInterval{BigFloat}, BigFloat}, Float64, Vector{Float64}}, Fun{Chebyshev{IntervalSets.ClosedInterval{BigFloat}, BigFloat}, BigFloat, Vector{BigFloat}}}
1 ─ %1 = ApproxFunBase.default_Fun(f, d)::Union{Fun{Chebyshev{IntervalSets.ClosedInterval{BigFloat}, BigFloat}, Float64, …
```

Fix type instability in constructors.jl

---

src/Space.jl

With this, the following works:
```julia
julia> transform(Chebyshev(), 1:2)
2-element Vector{Float64}:
1.5
-0.7071067811865476
```
Fix https://github.com/JuliaApproximation/ApproxFun.jl/issues/659

Convert to float in transform/itransform

---

Project.toml
src/Space.jl

Backport: Use mutable copies in transform/itransform

---

src/Spaces/ConstantSpace.jl
test/SpacesTest.jl

Also, evaluating a `Fun{<:ConstantSpace}` outside the domain will return zero after this, which is consistent with how other spaces behave.

First/last for ConstantSpace Fun

---

src/Spaces/DiracSpace.jl
test/SpacesTest.jl

Since a `Point` may be converted to a `Number`, we may allow evaluating a `Fun{<:PointSpace}` at a point as well, so that the following works now:
```julia
julia> f = Fun(PointSpace(1:3))
Fun(PointSpace([1, 2, 3]), [1, 2, 3])
julia> f(Point(1))
1
```

Evaluate Fun{<:PointSpace} using a Point

---

Project.toml
src/Fun.jl
src/Spaces/ConstantSpace.jl
test/SpacesTest.jl

After this, coefficients for non-constant `Fun`s can't be evaluated in a `ConstantSpace`.
The following works on master, but will be disallowed:
```julia
julia> coefficients(Fun(Chebyshev(0..1)), ConstantSpace(0..1))
2-element Vector{Float64}:
0.5
Inf
```
The newly added function `isconstantfun` is intended to be extended by downstream packages to provide more efficient implementations.

Add isconstantfun and check while converting to ConstantSpace

---

src/Fun.jl
test/SpacesTest.jl

This should be more correct, especially if `SumSpace`s are involved

Use values in iszero

---

src/Fun.jl
src/Operators/Operator.jl
src/Spaces/ConstantSpace.jl
src/Spaces/DiracSpace.jl
test/SpacesTest.jl
test/runtests.jl

Backport changes from #635, #634, #633, #632 and #631

Backport isconstant

---

Project.toml
src/Multivariate/Multivariate.jl

Fix JuliaApproximation/ApproxFun.jl#929.

Fix kron product on sum spaces

---

src/ApproxFunBase.jl

I don't understand how these were working without being imported (see https://discourse.julialang.org/t/query-regarding-namespaces-when-adding-a-method-using-a-macro/115392), but these should be explicitly imported before being extended.

Explicitly import extended functions

---

.github/workflows/CompatHelper.yml
.github/workflows/downgrade.yml
.github/workflows/downstream.yml
ApproxFunBaseTest/README.md
Project.toml
ext/ApproxFunBaseTestExt.jl
src/ApproxFunBase.jl
src/testutils.jl

After this, downstream packages don't need to depend explicitly on `ApproxFunBaseTest`, but may instead depend on the internal module `ApproxFunBase.TestUtils`, which is equivalent in functionality. The advantage is that the methods are defined in a package extension, so the package does not need to be maintained separately.

Convert ApproxFunBaseTest to a package extension

---

src/Operators/general/OperatorLayout.jl

Implemented blockbandwidths for adjoint operators

---

Project.toml
src/ApproxFunBase.jl

Since a method to `Number` is being added in this package, it needs to be imported explicitly.

Explicitly import `Number` before extending it
